/* Finance UI for the trusted-device edition of HSV GHW. */
(function(){
'use strict';
const C=FinanceCore;
const state={year:new Date().getFullYear(),filter:'all',search:'',detail:null,view:'overview',preview:null};
const money=n=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format((n||0)/100);
const E=escapeHtml, A=escapeHtmlAttr;
const euroInput=n=>((n||0)/100).toFixed(2);
const byId=id=>document.getElementById(id);
const read=id=>byId(id)?.value??'';
const button=(label,action,extra='',cls='btn btn-gh')=>`<button type="button" class="${cls}" data-fin="${action}" ${extra}>${label}</button>`;
const input=(id,label,value='',type='text',extra='')=>`<label class="fin-field"><span>${label}</span><input id="${id}" type="${type}" value="${A(value)}" ${extra}></label>`;
const amount=(id,label,value=0)=>input(id,label,euroInput(value),'number','min="0" max="10000000" step="0.01" inputmode="decimal" required');
function profile(){return isAdmin&&currentAdmin?getData().admins.find(a=>a.id===currentAdmin.id&&a.actief!==false):null;}
function access(){const a=profile();return a?.rol==='hoofd'?'write':a?.financeAccess||'none';}
function allowed(edit=false){return edit?access()==='write':['read','write'].includes(access());}
function requireAccess(edit=false){if(!allowed(edit))throw Error(edit?'Je hebt geen financiële bewerkrechten.':'Je hebt geen toegang tot de financiële administratie.');}
function onlyFinance(){return !!profile()?.financeOnly;}
function currentEntry(d){return d.finance.entries.find(e=>e.id===state.detail);}
function save(d){requireAccess(true);saveData(d);}
function statusLabel(e){return e.status==='settled'?'Afgerekend':e.status==='cancelled'?'Afgelast / vervallen':e.configured?'Gepland':'Bedrag invullen';}
function noticeError(err){showAppNotice(err.message||String(err),'warn',6500);}
const oldNormalize=ensureAdminData;
ensureAdminData=function(d){const permissions=new Map((d.admins||[]).map(a=>[a.id,{financeAccess:a.financeAccess,financeOnly:a.financeOnly}]));const out=oldNormalize(d);for(const a of out.admins){const p=permissions.get(a.id)||{};a.financeAccess=['none','read','write'].includes(p.financeAccess)?p.financeAccess:'none';a.financeOnly=p.financeOnly===true&&a.rol!=='hoofd';}C.sync(out);return out;};
const oldSave=saveData;
saveData=function(d){try{return oldSave(d);}catch(e){if(e.name==='QuotaExceededError')showAppNotice('Opslaan mislukt: de browseropslag is vol. Maak een back-up en verklein of verwijder bijlagen.','warn',10000);throw e;}};
const page=document.createElement('div');page.className='pv';page.id='pv-finance';byId('pv-admin-home').parentNode.appendChild(page);
const navButton=document.createElement('button');navButton.id='nav-finance';navButton.className='sb-btn';navButton.textContent='Financiën';navButton.style.display='none';navButton.onclick=()=>nav('finance');byId('admin-nav').after(navButton);
titles.finance='Financiën';ADMIN_PAGES.push('finance');
const oldNav=nav;
nav=function(p,...args){if(p==='finance'&&!allowed()){if(!isAdmin)openPin();else showAppNotice('Geen toegang tot financiën.','warn');return;}if(onlyFinance()&&ADMIN_PAGES.includes(p)&&!['finance','admin-home'].includes(p)){showAppNotice('Dit account heeft alleen financiële toegang.','warn');return;}if(p==='backup'&&!isHoofdAdmin()){showAppNotice('Volledige back-ups zijn alleen voor de hoofdbeheerder.','warn');return;}oldNav(p,...args);if(p==='finance')render();};
const oldAdminUi=updateAdminUi;
updateAdminUi=function(){oldAdminUi();navButton.style.display=allowed()?'flex':'none';if(onlyFinance())byId('admin-nav').style.display='none';byId('nav-backup').style.display=isHoofdAdmin()?'flex':'none';if(!allowed()){page.innerHTML='';document.querySelectorAll('.fin-pay-panel').forEach(el=>el.remove());}};
const oldHome=renderAdminHome;
renderAdminHome=function(){if(onlyFinance()){byId('admin-home-content').innerHTML=`<div class="card"><div class="stitle">Welkom ${E(currentAdmin.naam)}</div><p>Jouw toegang: ${access()==='write'?'financiën bekijken en bewerken':'financiën bekijken'}.</p>${button('Open financiën','open','','btn btn-g')}</div>`;return;}oldHome();if(allowed())byId('admin-home-content').insertAdjacentHTML('afterbegin',`<div class="card fin-home"><div><div class="stitle">Financiën</div><div class="sub">Begroting, wedstrijdafrekeningen en kasboek.</div></div>${button('Open financiën','open','','btn btn-g')}</div>`);};
const oldLogout=doLogout;
doLogout=function(){state.detail=null;state.preview=null;oldLogout();page.innerHTML='';};
const oldAccounts=renderAdminGegevensPane;
renderAdminGegevensPane=function(){return oldAccounts()+(isHoofdAdmin()?permissionsHtml():'');};
function permissionsHtml(){return `<div class="card"><div class="stitle">Toegang tot financiën</div><p class="sub">De hoofdbeheerder kan altijd bewerken. Je kunt andere gebruikers toegang geven tot alleen financiën.</p>${getData().admins.map(a=>`<div class="fin-permission"><strong>${E(a.naam)}</strong>${a.rol==='hoofd'?'<span>Hoofdbeheerder · bewerken</span>':`<label>Financiën<select data-fin-change="permission" data-id="${A(a.id)}"><option value="none" ${a.financeAccess==='none'?'selected':''}>Geen toegang</option><option value="read" ${a.financeAccess==='read'?'selected':''}>Alleen kijken</option><option value="write" ${a.financeAccess==='write'?'selected':''}>Kijken en bewerken</option></select></label><label><input type="checkbox" data-fin-change="finance-only" data-id="${A(a.id)}" ${a.financeOnly?'checked':''}> Alleen financiën, geen uitslagenbeheer</label>`}</div>`).join('')}<form id="fin-user-form"><h3>Financiële gebruiker toevoegen</h3><div class="fin-fields">${input('fin-user-name','Naam','','text','required')}${input('fin-user-code','Persoonlijke code','','password','required minlength="4" autocomplete="new-password"')}<label class="fin-field"><span>Rechten</span><select id="fin-user-right"><option value="read">Alleen kijken</option><option value="write">Kijken en bewerken</option></select></label></div><button class="btn btn-g" type="submit">Gebruiker toevoegen</button></form></div>`;}
function overview(){
 const d=getData(),s=C.summary(d,state.year),year=d.finance.years[state.year]||{},write=allowed(true);
 const entries=d.finance.entries.filter(e=>String(e.date||e.year).slice(0,4)===String(state.year)&&!e.seriesId);
 const filtered=entries.filter(e=>(state.filter==='all'||e.status===state.filter||e.kind===state.filter||(state.filter==='match'&&e.kind==='series'))&&`${e.title} ${e.category}`.toLowerCase().includes(state.search.toLowerCase())).sort((a,b)=>(a.date||'').localeCompare(b.date||'')||a.title.localeCompare(b.title));
 return `<div class="fin-heading"><div><span class="fin-eyebrow">VERENIGINGSADMINISTRATIE</span><h1>Grip op het jaar</h1><p class="sub">Van jaarbudget tot laatste wedstrijdafrekening.</p></div><label class="fin-year">Kalenderjaar<input id="fin-year" type="number" min="2000" max="2100" value="${state.year}" data-fin-change="year"></label></div>
 <div class="fin-metrics"><div class="fin-metric"><span>Jaarbudget + meegenomen</span><strong>${money(s.start)}</strong><small>${money(s.budget)} budget · ${money(s.carry)} meegenomen</small></div><div class="fin-metric"><span>Al uitgegeven · netto</span><strong>${money(s.net)}</strong><small>Kosten van afgerekende posten, na inschrijfgeld</small></div><div class="fin-metric"><span>Nog gereserveerd</span><strong>${money(s.reserved)}</strong><small>Bijdragen aan wedstrijden en overige plannen</small></div><div class="fin-metric fin-available ${s.free<0?'fin-negative':''}"><span>${s.free<0?'Begrotingstekort':'Vrij te besteden'}</span><strong>${money(s.free)}</strong><small>${s.free<0?'De plannen passen niet binnen het budget':'Na alle geplande en betaalde posten'}</small></div></div>
 <div class="fin-context"><span>Huidig saldo <b>${money(s.balance)}</b></span><span>Inschrijfgeld nog te ontvangen <b>${money(s.open)}</b></span><span>Inleg apart voor open prijzenpotten <b>${money(s.held)}</b></span><span>Extra budget uit losse seriedeelnames <b>${money(s.extra)}</b></span><span class="fin-local">Lokale administratie op deze pc</span></div>
 ${s.missing?`<div class="info">${s.missing} wedstrijd(en) hebben nog geen ingevulde begroting. Het beschikbare bedrag is daarom nog onvolledig.</div>`:''}
 ${s.unclassified?`<div class="info">Kies voor ${s.unclassified} seriedeelnemer(s) nog ‘hele serie’ of ‘los’. Ontvangen bedragen zonder keuze blijven apart gehouden.</div>`:''}
 ${!year.configured?'<div class="info">Vul eerst het ontvangen jaarbudget en eventueel het meegenomen bedrag in.</div>':''}
 <div class="fin-toolbar">${write?button('Jaarbudget instellen','budget')+button('+ Overige uitgave','new','','btn btn-g')+button('Jaarplanning downloaden','template')+button('Jaarplanning uploaden','import')+button('Viswateren','waters')+button('Dubbele wedstrijden controleren','duplicates'):''}${button('Excel-overzicht','excel')}${button('PDF-overzicht','pdf')}${isHoofdAdmin()?button('Back-up downloaden','backup'):''}${isHoofdAdmin()?button('Toegangsrechten','rights'):''}</div>
 <div class="card fin-ledger"><div class="fin-list-heading"><h2>Geplande en betaalde posten</h2><span>${entries.length} posten</span></div><div class="fin-filters"><label>Zoeken<input id="fin-search" placeholder="Wedstrijd, feestavond, materiaal…" value="${A(state.search)}"></label><label>Filter<select data-fin-change="filter"><option value="all">Alle posten</option>${[['planned','Gepland'],['settled','Afgerekend'],['cancelled','Afgelast / vervallen'],['match','Wedstrijden'],['expense','Overige uitgaven']].map(([v,l])=>`<option value="${v}" ${state.filter===v?'selected':''}>${l}</option>`).join('')}</select></label>${button('Zoeken','search')}</div><div class="fin-table-head"><span>Post / datum</span><span>Status</span><span>Begroot</span><span>Werkelijk netto</span></div>${filtered.length?filtered.map(e=>`<button class="fin-row" data-fin="detail" data-id="${A(e.id)}"><span class="fin-post"><strong>${E(e.title)}</strong><small>${E(e.date?nlDatum(e.date):'Datum nog onbekend')} · ${E(e.category||'Overig')}</small></span><span><span class="fin-badge ${e.status}">${statusLabel(e)}</span></span><span><small class="fin-mobile-label">Begroot</small>${e.configured?money(e.planned):'Nog invullen'}</span><span><small class="fin-mobile-label">Werkelijk netto</small>${e.status==='settled'?money(C.stats(e).net):'—'}</span></button>`).join(''):'<div class="fin-empty">Geen posten gevonden. Importeer je jaarplanning of voeg een uitgave toe.</div>'}</div>
 <p class="fin-footnote">Een ontvangen inleg hoort bij de prijzenpot. Een reservering vervalt bij afrekening of afgelasting. Maak regelmatig een back-up; browsergegevens worden niet automatisch gedeeld.</p>`;
}
function budgetHtml(){const y=getData().finance.years[state.year]||{};return `${back()}<div class="card"><h2>Jaarbudget ${state.year}</h2><p class="sub">Vul het daadwerkelijk gestorte budget in. Het bedrag uit het vorige jaar kies je zelf.</p><form id="fin-budget-form"><div class="fin-fields">${amount('fin-budget','Ontvangen jaarbudget',y.budget)}${amount('fin-carry','Meegenomen uit vorig jaar',y.carry)}</div><button class="btn btn-g">Opslaan</button></form></div>`;}
function back(){return button('← Jaaroverzicht','back','', 'btn btn-gh fin-back');}
function detailHtml(){
 const d=getData(),e=currentEntry(d);if(!e){state.view='overview';return overview();}if(e.kind==='series')return seriesDetailHtml(e,d);if(e.seriesId)return seriesMatchHtml(e,d);const write=allowed(true),s=C.stats(e),disabled=write?'':'disabled';
 return `${back()}<div class="card"><div class="fin-detail-heading"><div><span class="fin-eyebrow">${e.kind==='match'?'WEDSTRIJDAFREKENING':'OVERIGE UITGAVE'}</span><h1>${E(e.title)}</h1></div><span class="fin-badge ${e.status}">${statusLabel(e)}</span></div><form id="fin-entry-form"><fieldset ${disabled}><div class="fin-fields">${input('fin-title','Omschrijving',e.title,'text','required')}${input('fin-date','Datum',e.date,'date',e.kind==='match'?'required':'')}${e.kind==='expense'?input('fin-category','Categorie',e.category,'text','list="fin-categories" required'):''}${amount('fin-planned',e.kind==='match'?'Begrote bijdrage vereniging':'Begrote kosten',e.planned)}${e.kind==='match'?amount('fin-fee','Inleg per visser',e.fee):''}</div><datalist id="fin-categories"><option>Feestavond</option><option>Materiaal</option><option>Muntjes</option><option>Benzine</option><option>Overig</option></datalist>${e.kind==='match'&&Object.keys(e.payments).length?'<p class="sub">Een gewijzigd tarief geldt voor nog openstaande betalingen. Reeds ontvangen bedragen blijven behouden.</p>':''}<label class="fin-field"><span>Notitie</span><textarea id="fin-note" rows="2">${E(e.note||'')}</textarea></label>${write?'<button class="btn btn-g" type="submit">Gegevens opslaan</button>':''}</fieldset></form></div>
 ${e.kind==='match'?`<div class="card"><h2>Prijzenpot</h2><div class="fin-pot"><div><span>Ontvangen inschrijfgeld</span><strong>${money(s.income)}</strong></div><div><span>Bijdrage vereniging</span><strong>${money(e.planned)}</strong></div><div><span>Beschikbare prijzenpot</span><strong>${money(s.income+e.planned)}</strong></div></div><p class="sub">Nog te ontvangen: ${money(s.open)}. Openstaande betalingen tellen pas mee zodra ze zijn ontvangen.</p>${e.status==='settled'?`<p>Uitgekeerd: <b>${money(e.payout)}</b>. ${s.income+e.planned-e.payout>=0?'Terug naar vrij budget':'Extra nodig uit budget'}: <b>${money(Math.abs(s.income+e.planned-e.payout))}</b>.</p>`:''}${write&&e.status!=='cancelled'?`${e.matchId?button('Betalingen bij deelnemers openen','participants',`data-id="${A(e.matchId)}"`):e.agendaId?button('Wedstrijdinvoer starten','start-match',`data-id="${A(e.agendaId)}"`):''}`:''}${paymentList(e,d,false)}</div>`:''}
 <div class="card"><h2>${e.status==='settled'?'Afrekening':'Post afrekenen'}</h2>${write&&e.status!=='cancelled'?`<form id="fin-settle-form"><div class="fin-fields">${amount('fin-payout',e.kind==='match'?'Totaal uitgekeerd prijzengeld':'Werkelijk betaald eindtotaal',e.status==='settled'?e.payout:e.kind==='match'?s.income+e.planned:e.planned)}</div><p class="sub">Na afrekening vervalt de reservering. ${e.kind==='match'?'Openstaande inschrijfgelden blijven zichtbaar.':''}</p><button class="btn btn-g">${e.status==='settled'?'Afrekening aanpassen':'Afrekenen'}</button></form>`:`<p>${e.status==='settled'?`Werkelijk betaald: <strong>${money(e.payout)}</strong>`:e.status==='cancelled'?'De reservering is vrijgegeven.':'Deze post is nog niet afgerekend.'}</p>`}<div class="fin-toolbar">${write&&e.status==='planned'?button(e.kind==='match'?'Wedstrijd afgelasten':'Post laten vervallen','cancel'):''}${write&&e.status!=='planned'?button('Heropenen als gepland','reopen'):''}</div></div>
 <div class="card"><h2>Bonnen en bestanden</h2><p class="sub">Optioneel een foto of PDF, maximaal 750 KB per bestand en 1,5 MB aan bijlagen totaal. Ze worden meegenomen in de gegevensback-up.</p>${e.attachments.map((a,i)=>`<div class="fin-attachment"><span>${E(a.name)} <small>(${Math.ceil(a.size/1024)} KB)</small></span>${button('Downloaden','attachment',`data-index="${i}"`)}${write?button('Verwijderen','remove-attachment',`data-index="${i}"`):''}</div>`).join('')}${write?'<label class="fin-field"><span>Bon toevoegen</span><input type="file" id="fin-attachment-file" accept="image/jpeg,image/png,application/pdf"></label>':''}</div>`;
}

function seriesDetailHtml(e,d){
 const children=d.finance.entries.filter(c=>c.seriesId===e.id),full=C.received(e),loose=children.reduce((n,c)=>n+C.stats(c).extra,0),w=allowed(true);
 return back()+'<div class="card"><span class="fin-eyebrow">ÉÉN AFREKENING VOOR DE HELE SERIE</span><h1>'+E(e.title)+'</h1><span class="fin-badge '+e.status+'">'+statusLabel(e)+'</span>'+ (e.migrationNotice?'<p class="info">Controleer de eenmalige verenigingsbijdrage. Eerdere bedragen per wedstrijd: '+(e.previousContributions||[]).map(money).join(', ')+'. Bestaande ontvangsten blijven bewaard; kies hieronder per visser de deelname.</p>':'')+
 '<form id="fin-series-form"><fieldset '+(w?'':'disabled')+'><div class="fin-fields">'+amount('fin-series-planned','Verenigingsbijdrage voor de hele serie',e.planned)+amount('fin-series-fee','Inleg per visser voor de hele serie',e.fee)+amount('fin-series-aow','Inleg hele serie · AOW-tarief',e.feeAow||0)+amount('fin-series-loose','Inleg per losse wedstrijd',e.looseFee)+'</div><p class="sub">Het AOW-tarief wordt in een volgende stap per visser toegepast; nu wordt het alleen vastgelegd.</p><label class="fin-field"><span>Notitie</span><textarea id="fin-series-note">'+E(e.note||'')+'</textarea></label>'+(w?'<button class="btn btn-g">Serietarieven opslaan</button>':'')+'</fieldset></form></div>'+ 
 '<div class="card"><h2>Gezamenlijke prijzenpot</h2><p class="sub">'+Object.values(e.enrollments).filter(v=>v==='series').length+' deelnemers voor de hele serie · '+Object.keys(e.payments).length+' seriebetalingen ontvangen.</p><div class="fin-pot"><div><span>Ontvangen serie-inschrijfgeld</span><strong>'+money(full)+'</strong></div><div><span>Eenmalige verenigingsbijdrage</span><strong>'+money(e.planned)+'</strong></div><div><span>Beschikbare prijzenpot</span><strong>'+money(full+e.planned)+'</strong></div></div><p>Losse deelnemers: <b>'+money(loose)+'</b> extra beschikbaar verenigingsbudget. Dit geld zit niet in de prijzenpot.</p><p class="sub">Nog te ontvangen voor hele-seriedeelname: '+money(C.outstanding(e))+'. De tarieven gelden voor openstaande betalingen; ontvangen bedragen blijven behouden.</p></div>'+ 
 '<div class="card"><h2>Wedstrijden en deelnemers</h2><p class="sub">Kies bij de deelnemers één keer ‘hele serie’ of ‘los’. Een seriebetaling geldt voor alle wedstrijden binnen deze serie.</p>'+children.map(c=>'<div class="fin-payment"><span><strong>'+E(c.title)+'</strong><small>'+E(nlDatum(c.date))+' · Los ontvangen '+money(C.stats(c).extra)+'</small></span>'+button(w?'Deelnemers / betalingen':'Bekijken','detail','data-id="'+A(c.id)+'"')+'</div>').join('')+(children.length?'':'<p class="sub">Er zijn nog geen wedstrijden gekoppeld. Gebruik in de agenda en Excel dezelfde serienaam en hetzelfde jaar.</p>')+'</div>'+ 
 '<div class="card"><h2>Prijzengeld hele serie</h2>'+(w&&e.status!=='cancelled'?'<form id="fin-settle-form">'+amount('fin-payout','Totaal uitgekeerd prijzengeld',e.payout||full+e.planned)+'<p class="sub">Losse inschrijfgelden worden niet uitgekeerd. Een restant van de serieprijzenpot komt vrij in het verenigingsbudget.</p><button class="btn btn-g">'+(e.status==='settled'?'Afrekening aanpassen':'Serie afrekenen')+'</button></form>':'<p>Uitgekeerd: '+money(e.payout)+'</p>')+'<div class="fin-toolbar">'+(w?(e.status==='planned'?button('Hele serie afgelasten','cancel'):button('Heropenen als gepland','reopen')):'')+'</div></div>';
}
function seriesMatchHtml(e,d){const p=C.seriesFor(d,e),w=allowed(true);return button('← '+E(p.title),'detail','data-id="'+A(p.id)+'"')+'<div class="card fin-series-payments"><h1>'+E(e.title)+'</h1><p>Onderdeel van '+E(p.title)+'. De bijdrage en prijzenpot worden één keer bij de hele serie bijgehouden.</p><p>Hele serie: <b>'+money(p.fee)+'</b> per visser · losse deelname: <b>'+money(p.looseFee)+'</b> per wedstrijd.</p>'+(!p.configured?'<p class="info">Vul eerst de tarieven bij de serie in.</p>':'')+paymentList(e,d,w)+(w&&!onlyFinance()?(e.matchId?button('Open wedstrijdinvoer','participants','data-id="'+A(e.matchId)+'"'):e.agendaId?button('Wedstrijdinvoer starten','start-match','data-id="'+A(e.agendaId)+'"'):''):'')+'</div>';}
function seriesPaymentList(e,d,editable){
 const p=C.seriesFor(d,e);if(!p)return '';const ids=[...new Set(e.members||[])];if(!ids.length)return '<p class="sub">De deelnemers verschijnen na invoer bij deze wedstrijd.</p>';
 return '<div class="fin-payment-list">'+ids.map(id=>{const mode=p.enrollments[id]||'',target=mode==='series'?p:e,paid=Object.hasOwn(target.payments,id),v=d.vissers.find(v=>v.id===id),legacy=mode?'':e.payments[id];return '<div class="fin-payment fin-series-person"><span><strong>'+E(v?vNaam(v):'Verwijderde visser')+'</strong><small>'+(mode?(paid?money(target.payments[id].amount)+' ontvangen':money(mode==='series'?p.fee:p.looseFee)+' openstaand'):(legacy?money(legacy.amount)+' ontvangen, deelname nog kiezen':'Deelname nog kiezen'))+'</small></span>'+(editable?'<label>Deelname<select data-fin-change="series-mode" data-id="'+A(e.id)+'" data-member="'+A(id)+'"><option value="">Kies deelname</option><option value="series" '+(mode==='series'?'selected':'')+'>Hele serie</option><option value="loose" '+(mode==='loose'?'selected':'')+'>Losse wedstrijd</option></select></label><label><input type="checkbox" data-fin-change="paid" data-id="'+A(e.id)+'" data-member="'+A(id)+'" '+(paid?'checked':'')+' '+(!mode||!p.configured||p.status==='cancelled'?'disabled':'')+'> '+(mode==='series'?'Serie betaald':'Betaald')+'</label>':'<span class="fin-badge">'+(mode==='series'?'Hele serie':mode==='loose'?'Los':'Nog te kiezen')+' · '+(paid?'Betaald':'Open')+'</span>')+'</div>';}).join('')+'</div>';
}
function refreshSeriesPayment(el,e){if(el.closest('.fin-pay-panel'))mountPayments();else{state.detail=e.id;state.view='detail';render();}}

function paymentList(e,d,editable){
 if(e.seriesId)return seriesPaymentList(e,d,editable);
 const ids=[...new Set(e.members||[])];if(!ids.length)return '<p class="sub">De deelnemers verschijnen zodra ze in de wedstrijd zijn ingevoerd.</p>';
 return `<div class="fin-payment-list">${ids.map(id=>{const v=d.vissers.find(v=>v.id===id),paid=Object.prototype.hasOwnProperty.call(e.payments,id);return `<div class="fin-payment"><span>${E(v?vNaam(v):'Verwijderde visser')}<small>${paid?money(e.payments[id].amount)+' ontvangen':money(e.fee)+' openstaand'}</small></span>${editable?`<label><input type="checkbox" data-fin-change="paid" data-id="${A(e.id)}" data-member="${A(id)}" ${paid?'checked':''}> Betaald</label>`:`<span class="fin-badge ${paid?'settled':'planned'}">${paid?'Betaald':'Open'}</span>`}</div>`;}).join('')}</div>`;
}
function mountPayments(){
 document.querySelectorAll('.fin-pay-panel').forEach(el=>el.remove());if(!allowed(true)||!invoerState?.wId)return;
 const d=getData(),e=C.matchEntry(d,invoerState.wId);if(!e||e.status==='cancelled')return;
 e.members=[...new Set([...e.members,...(invoerState.rows||[]).filter(r=>r.selected&&!r.afwezig).map(r=>r.vid)])];
 const el=document.createElement('section');el.className='card fin-pay-panel';el.innerHTML=`<div class="fin-list-heading"><h2>Inschrijfgeld deelnemers</h2><span>${money(e.fee)} per visser</span></div>${!e.configured?'<p class="info">Stel eerst de inleg en verenigingsbijdrage in via de afrekening.</p>':''}${button('Wedstrijdafrekening','detail',`data-id="${A(e.id)}"`)}${paymentList(e,d,true)}`;byId('invoer-form')?.appendChild(el);
}
const oldInvoer=renderInvoerForm;
renderInvoerForm=function(){oldInvoer();mountPayments();};
function render(){if(!allowed()){page.innerHTML='';return;}page.innerHTML=state.view==='detail'?detailHtml():state.view==='duplicates'?duplicatesHtml():state.view==='budget'?budgetHtml():state.view==='import'?importHtml():state.view==='waters'?watersHtml():state.view==='rights'&&isHoofdAdmin()?back()+permissionsHtml():overview();document.querySelector('.page').scrollTop=0;}
function openDetail(id){requireAccess();state.detail=id;state.view='detail';nav('finance');}
function newExpense(){requireAccess(true);const d=getData(),id='expense-'+uid();d.finance.entries.push({id,kind:'expense',title:'Nieuwe uitgave',date:`${state.year}-01-01`,category:'Overig',planned:0,payout:0,status:'planned',configured:false,payments:{},members:[],attachments:[]});save(d);openDetail(id);}
function duplicatesHtml(){const pairs=FinancePlan.duplicates(getData(),state.year);return back()+'<div class="card"><h2>Mogelijk dubbele wedstrijden · '+state.year+'</h2><p>Deze regels staan op dezelfde datum, maar zijn nog niet gekoppeld. Kies per paar of ze dezelfde wedstrijd zijn. Er wordt niets automatisch samengevoegd.</p><p class="sub">Bij koppelen blijven uitslagen, betalingen en bonnen behouden. Bij een afwijkende wedstrijdvorm gebruik je de uitslag als basis, zodat de deelnemersindeling behouden blijft.</p></div>'+pairs.map(p=>'<div class="card"><h3>'+E(nlDatum(p.date))+'</h3><p><strong>Agenda:</strong> '+E(p.agendaTitle)+' · '+E(p.agendaForm)+'</p><p><strong>Uitslagen:</strong> '+E(p.resultTitle)+' · '+E(p.resultForm)+'</p><div class="fin-toolbar">'+button('Koppelen · agenda als basis','resolve-duplicate','data-key="'+A(p.key)+'" data-choice="agenda" '+(p.agendaForm!==p.resultForm?'disabled':''))+button('Koppelen · uitslag als basis','resolve-duplicate','data-key="'+A(p.key)+'" data-choice="result"')+button('Apart houden','resolve-duplicate','data-key="'+A(p.key)+'" data-choice="separate"')+'</div></div>').join('')+(!pairs.length?'<div class="card"><p>Geen onbeoordeelde dubbele paren gevonden. Je kunt de bijgewerkte jaarplanning downloaden.</p>'+button('Jaarplanning downloaden','template')+'</div>':'');}
function importHtml(){const p=state.preview,err=state.importErrors;const labels={title:'Naam',date:'Datum',endDate:'Einddatum',form:'Vorm',series:'Serie',rod:'Hengeltype',water:'Viswater',location:'Locatie loting',gather:'Lotingtijd',start:'Starttijd',end:'Eindtijd',planned:'Begroot',fee:'Inleg',seriesFee:'Inleg hele serie',seriesFeeAow:'Inleg hele serie AOW'};const val=(k,v)=>v===null||v===undefined||v===''?'—':['planned','fee','seriesFee','seriesFeeAow'].includes(k)?money(v):k==='form'?(FinancePlan.forms[v]||v):String(v);
 const warnings=w=>w?.length?'<div class="fin-warnings"><strong>Overgeslagen</strong>'+w.map(t=>'<small>'+E(t)+'</small>').join('')+'</div>':'';
 let html=back()+'<div class="card"><h2>Jaarplanning · '+state.year+'</h2><p>Download de planning, vul aan en upload het bestand terug. Eén blad vult agenda én begroting; het blad Viswateren vult lotingplek en tijden automatisch aan.</p><p class="sub">Verplicht per regel: Vorm, Datum en een naam. Alles anders mag leeg (“nog invullen”). Bij een serie zet je de bedragen op één willekeurige regel. Bestaande betalingen, uitslagen en bonnen blijven bewaard.</p><div class="fin-toolbar">'+button('Jaarplanning downloaden','template')+button('Viswateren beheren','waters')+'</div><label class="fin-field"><span>Ingevulde jaarplanning uploaden (.xlsx)</span><input type="file" id="fin-import-file" accept=".xlsx"></label></div>';
 if(err)html+='<div class="card fin-errors"><h2>'+E(err.message)+'</h2><p class="sub">Verbeter de regels in Excel en upload opnieuw. Er is niets gewijzigd.</p><table><thead><tr><th>Blad</th><th>Rij</th><th>Kolom</th><th>Melding</th></tr></thead><tbody>'+err.errors.map(x=>'<tr><td>'+E(x.sheet||'')+'</td><td>'+x.line+'</td><td>'+E(x.column||'')+'</td><td>'+E(x.message)+'</td></tr>').join('')+'</tbody></table>'+warnings(err.warnings)+'</div>';
 if(p){const status={new:'Nieuw',same:'Ongewijzigd',update:'Gewijzigd',error:'Nog oplossen'};
  html+='<div class="card"><h2>Controleer de verschillen</h2><p>Jaar '+p.year+'. Kies welke wijzigingen je wilt overnemen. Wijzigingen binnen één serie worden samen verwerkt.</p>'+warnings(p.warnings)
  +(p.budget.length?'<div class="fin-import-row"><input type="checkbox" checked disabled><span><strong>Jaarbudget '+p.year+'</strong>'+p.budget.map(b=>'<small>'+E(b.label)+': '+money(b.before)+' → '+money(b.after)+'</small>').join('')+'</span></div>':'')
  +p.items.map(x=>'<div class="fin-import-row'+(x.error?' error':'')+'"><input type="checkbox" data-fin-import="'+x.row.line+'" '+(x.action==='same'||x.error?'disabled':'checked')+'><span><strong>'+E(x.row.title||x.row.series)+'</strong><small>Rij '+x.row.line+' · '+E(x.row.date?nlDatum(x.row.date):'Datum nog onbekend')+' · '+status[x.action]+'</small>'+(x.error?'<small class="fin-error-text">'+E(x.error)+'</small>':'')+x.changes.map(c=>'<small>'+labels[c.key]+': '+E(val(c.key,c.before))+' → '+E(val(c.key,c.after))+'</small>').join('')+(x.candidates?.length?'<label class="fin-field"><span>'+(x.error?'Koppel aan een bestaande post of vul een datum in Excel in.':'Is dit een nieuwe post of een gewijzigde bestaande post?')+'</span><select data-plan-map="'+x.row.line+'"><option value="?">Kies een koppeling</option>'+(x.error?'':'<option value="">Nieuwe post</option>')+x.candidates.map(e=>'<option value="'+A(e.id)+'">'+E(e.title+' · '+(e.date?nlDatum(e.date):'Geen datum'))+'</option>').join('')+'</select></label>':'')+'</span></div>').join('')
  +(p.waters.some(w=>w.action!=='same')?'<h3>Viswateren</h3>'+p.waters.filter(w=>w.action!=='same').map(w=>'<div class="fin-import-row"><input type="checkbox" checked disabled><span><strong>'+E(w.name)+'</strong><small>'+(w.action==='new'?'Nieuw':'Gewijzigd')+' · '+E([w.location,w.gather,w.start,w.end].filter(Boolean).join(' · ')||'geen standaardwaarden')+'</small></span></div>').join(''):'')
  +(p.missing.length?'<h3>Ontbreekt in nieuwe upload</h3><p>Deze posten blijven behouden, tenzij je hieronder aangeeft dat ze vervallen.</p>'+p.missing.map(e=>'<label class="fin-import-row"><input type="checkbox" data-plan-remove="'+A(e.id)+'"><span>'+E(e.title)+'<small>'+E(e.date?nlDatum(e.date):'Geen datum')+' · Laten vervallen en reservering vrijgeven</small></span></label>').join(''):'')
  +'<div class="fin-toolbar">'+button('Geselecteerde wijzigingen overnemen','apply-import','','btn btn-g')+button('Annuleren','clear-import')+'</div></div>';}
 return html;}
function watersHtml(){const d=getData(),waters=FinanceWaters.list(d),w=allowed(true);return back()+'<div class="card"><h2>Viswateren</h2><p>Per viswater één lotingplek en vaste tijden. Laat je die velden in de jaarplanning leeg, dan vult de upload ze hieruit aan. De tabel is voorgevuld uit je bestaande agenda; corrigeer wat niet klopt.</p>'+(waters.length?'<div class="fin-table-head fin-waters-head"><span>Viswater</span><span>Locatie loting</span><span>Loting</span><span>Start</span><span>Einde</span><span></span></div>'+waters.map(x=>'<div class="fin-water-row" data-water="'+A(x.name)+'"><input value="'+A(x.name)+'" data-water-field="name" '+(w?'':'disabled')+'><input value="'+A(x.location)+'" data-water-field="location" placeholder="Nog invullen" '+(w?'':'disabled')+'><input value="'+A(x.gather)+'" data-water-field="gather" placeholder="uu:mm" '+(w?'':'disabled')+'><input value="'+A(x.start)+'" data-water-field="start" placeholder="uu:mm" '+(w?'':'disabled')+'><input value="'+A(x.end)+'" data-water-field="end" placeholder="uu:mm" '+(w?'':'disabled')+'>'+(w?button('Verwijderen','remove-water','data-name="'+A(x.name)+'"'):'')+'</div>').join(''):'<p class="sub">Nog geen viswateren. Voeg er een toe of upload een jaarplanning met het blad Viswateren.</p>')+(w?'<form id="fin-water-form" class="fin-fields">'+input('fin-water-name','Nieuw viswater','','text','required')+input('fin-water-location','Locatie loting')+'<button class="btn btn-g">Toevoegen</button></form>':'')+'</div>';}
let importSequence=0;
async function readImport(file){requireAccess(true);const seq=++importSequence;state.preview=null;state.importErrors=null;if(!file)return;try{if(file.size>8*1024*1024)throw Error('Het bestand is te groot (maximaal 8 MB).');const wb=new ExcelJS.Workbook();await wb.xlsx.load(await file.arrayBuffer());if(seq!==importSequence)return;requireAccess(true);const plan=FinancePlan.read(wb);if(plan.rows.length>1000)throw Error('Maximaal 1000 posten per upload.');state.preview=FinancePlan.preview(getData(),plan);state.planSnapshot=localStorage.getItem(SK);render();}catch(e){if(seq===importSequence){state.preview=null;if(e.errors){state.importErrors={message:e.message,errors:e.errors,warnings:e.warnings||[]};render();return;}render();}throw e;}}
document.addEventListener('change',ev=>{const el=ev.target;if(!el.matches('[data-plan-map]'))return;try{requireAccess(true);if(el.value==='?')return;const p=state.preview,mapping={...p.mapping,[el.dataset.planMap]:el.value};state.preview=FinancePlan.preview(getData(),p.plan,mapping);render();}catch(e){noticeError(e);}});
async function downloadWorkbook(wb,name){try{const src=getShareLogoSrc();if(src.startsWith('data:image/')){const id=wb.addImage({base64:src,extension:src.includes('image/png')?'png':'jpeg'});const sheet=wb.getWorksheet('Jaarplanning')||wb.getWorksheet('Uitleg')||wb.getWorksheet('Jaaroverzicht');if(sheet){const img=new Image();await new Promise((ok,no)=>{img.onload=ok;img.onerror=no;img.src=src;});const h=55,w=h*img.naturalWidth/img.naturalHeight;sheet.addImage(id,{tl:{col:sheet.name==='Jaarplanning'?13:3,row:0},ext:{width:w,height:h}});}}}catch(_){}const bytes=await wb.xlsx.writeBuffer();triggerBlobDownload(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),name);}
function sheetStyle(ws){ws.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};ws.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF203B43'}};ws.getRow(1).height=28;ws.views=[{state:'frozen',ySplit:1}];ws.columns.forEach(c=>c.width=24);}
async function template(){requireAccess(true);const pairs=FinancePlan.duplicates(getData(),state.year);if(pairs.length&&!confirm('Er zijn '+pairs.length+' mogelijk dubbele wedstrijdparen. Annuleren opent de controle per paar. Toch nu downloaden?')){state.view='duplicates';render();return;}const wb=await FinancePlan.workbook(ExcelJS,getData(),state.year);await downloadWorkbook(wb,'HSV_GHW_Jaarplanning_'+state.year+'.xlsx');}
function reportData(){requireAccess();const d=getData(),s=C.summary(d,state.year);return {d,s,entries:d.finance.entries.filter(e=>String(e.date||e.year).slice(0,4)===String(state.year)).sort((a,b)=>a.date.localeCompare(b.date))};}
async function excelReport(){const {s,entries}=reportData(),wb=new ExcelJS.Workbook(),w=wb.addWorksheet('Jaaroverzicht');[['Jaaroverzicht',state.year],['Ontvangen jaarbudget',s.budget/100],['Meegenomen uit vorig jaar',s.carry/100],['Inschrijfgeld ontvangen',s.income/100],['Uitbetalingen en uitgaven',s.out/100],['Al uitgegeven netto',s.net/100],['Huidig saldo',s.balance/100],['Nog gereserveerd',s.reserved/100],['Vrij te besteden',s.free/100],['Inschrijfgeld openstaand',s.open/100],['Wedstrijden zonder begroting',s.missing],['Inleg open prijzenpotten',s.held/100],['Extra budget losse seriedeelnemers',s.extra/100],['Let op','Financiële gegevens; alleen delen met bevoegden.']].forEach(r=>w.addRow(r));sheetStyle(w);w.getColumn(1).width=36;for(let i=2;i<=10;i++)w.getCell(i,2).numFmt='€ #,##0.00';const p=wb.addWorksheet('Posten');p.addRow(['Datum','Omschrijving','Categorie','Status','Begroot','Ontvangen inleg','Uitbetaald','Netto kosten','Gereserveerd','Open inschrijfgeld','Losse serie-inleg naar budget','Notitie']);entries.forEach(e=>{const t=C.stats(e);p.addRow([e.date,e.title,e.category,statusLabel(e),e.planned/100,t.income/100,t.out/100,t.net/100,t.reserved/100,t.open/100,(t.extra||0)/100,e.note||'']);});sheetStyle(p);for(let c=5;c<=11;c++)p.getColumn(c).numFmt='€ #,##0.00';await downloadWorkbook(wb,`HSV_GHW_Financien_${state.year}.xlsx`);}
async function pdfReport(){
 const {s,entries}=reportData(),{PDFDocument,StandardFonts,rgb}=PDFLib,pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);let p,y,pageNum=0;
 const safe=t=>String(t).replace(/[^\x20-\x7e\u00a0-\u00ff€]/g,'-');
 const text=(t,x,yy,size=10,b=false,color=rgb(.12,.2,.23))=>p.drawText(safe(t),{x,y:yy,size,font:b?bold:font,color});
 let logo=null;try{const src=getShareLogoSrc();if(src.startsWith('data:image/jpeg'))logo=await pdf.embedJpg(src);else if(src.startsWith('data:image/png'))logo=await pdf.embedPng(src);}catch(_){}
 function next(){p=pdf.addPage([595.28,841.89]);pageNum++;y=745;if(logo){const dims=logo.scaleToFit(58,58);p.drawImage(logo,{x:495,y:763,width:dims.width,height:dims.height});}text('HSV Groot Hoeksche Waard',40,799,15,true);text(`Financieel jaaroverzicht ${state.year}`,40,776,12);text(`Vertrouwelijk | ${new Date().toLocaleDateString('nl-NL')} | pagina ${pageNum}`,40,28,8);}
 const wrap=(t,width,size=10)=>{const words=safe(t).split(/\s+/),lines=[];let line='';for(const word of words){if(font.widthOfTextAtSize((line?line+' ':'')+word,size)>width&&line){lines.push(line);line=word;}else line+=(line?' ':'')+word;}lines.push(line);return lines;};
 next();for(const [label,val] of [['Jaarbudget + meegenomen',s.start],['Al uitgegeven netto',s.net],['Huidig saldo',s.balance],['Nog gereserveerd',s.reserved],['Vrij te besteden',s.free],['Inschrijfgeld nog te ontvangen',s.open],['Inleg open prijzenpotten',s.held],['Extra budget losse seriedeelnemers',s.extra]]){text(label,40,y,11,label==='Vrij te besteden');text(money(val),410,y,11,true);y-=25;}if(s.missing){text(`${s.missing} wedstrijd(en) zonder ingevulde begroting.`,40,y,10,true);y-=22;}y-=15;
 const head=()=>{text('Post / datum',40,y,10,true);text('Begroot',320,y,10,true);text('Netto betaald',421,y,10,true);y-=22;};head();
 for(const e of entries){const lines=wrap(e.title,260);const h=Math.max(58,lines.length*13+34);if(y-h<55){next();head();}lines.forEach((l,i)=>text(l,40,y-i*13,10,true));text(`${e.date} | ${statusLabel(e)}`,40,y-lines.length*13-3,9);text(e.configured?money(e.planned):'Niet ingevuld',320,y,10);text(e.status==='settled'?money(C.stats(e).net):'-',421,y,10);y-=h;}
 if(y<110)next();wrap('Netto betaald betreft afgerekende prijzenpotten en uitgaven. Losse serie-inleg verhoogt het vrije budget en zit niet in de prijzenpot. Openstaande betalingen tellen nog niet mee.',510,9).forEach(l=>{text(l,40,y,9);y-=13;});triggerBlobDownload(new Blob([await pdf.save()],{type:'application/pdf'}),`HSV_GHW_Financien_${state.year}.pdf`);
}
async function addAttachment(file){requireAccess(true);if(!file)return;if(!['image/jpeg','image/png','application/pdf'].includes(file.type))throw Error('Kies een JPG, PNG of PDF.');if(file.size>750*1024)throw Error('Dit bestand is groter dan 750 KB. Verklein het eerst.');const d=getData(),size=d.finance.entries.flatMap(e=>e.attachments).reduce((s,a)=>s+a.size,0);if(size+file.size>1536*1024)throw Error('Maximaal 1,5 MB aan bijlagen. Maak een back-up en verwijder oude bijlagen of verklein de foto.');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Bestand kon niet worden gelezen.'));reader.readAsDataURL(file);});const fresh=getData(),e=currentEntry(fresh);if(!e)throw Error('Post niet meer beschikbaar.');e.attachments.push({name:file.name,type:file.type,size:file.size,data});save(fresh);render();}
async function action(name,el){
 requireAccess();const d=getData(),e=currentEntry(d);
 switch(name){
 case 'open':state.view='overview';nav('finance');return;
 case 'back':state.view='overview';state.detail=null;render();return;
 case 'detail':openDetail(el.dataset.id);return;
 case 'budget':requireAccess(true);state.view='budget';render();return;
 case 'new':newExpense();return;
 case 'search':state.search=read('fin-search');render();return;
 case 'rights':if(!isHoofdAdmin())throw Error('Alleen de hoofdbeheerder beheert rechten.');state.view='rights';render();return;
 case 'import':requireAccess(true);state.view='import';state.preview=null;state.importErrors=null;nav('finance');return;
 case 'waters':requireAccess();state.view='waters';render();return;
 case 'remove-water':requireAccess(true);if(!confirm('Viswater "'+el.dataset.name+'" uit de tabel verwijderen? Bestaande wedstrijden veranderen niet.'))return;FinanceWaters.remove(d,el.dataset.name);save(d);render();return;
 case 'duplicates':requireAccess(true);state.view='duplicates';render();return;
 case 'resolve-duplicate':requireAccess(true);save(FinancePlan.resolveDuplicate(d,state.year,el.dataset.key,el.dataset.choice));render();showAppNotice(el.dataset.choice==='separate'?'De wedstrijden blijven apart.':'Gekoppeld. De volgende download bevat één regel voor deze wedstrijd.');return;
 case 'template':await template();return;
 case 'clear-import':state.preview=null;state.importErrors=null;render();return;
 case 'apply-import':{requireAccess(true);if(!state.preview)throw Error('Kies eerst een bestand.');if(localStorage.getItem(SK)!==state.planSnapshot)throw Error('Gegevens zijn sinds de controle gewijzigd. Upload het bestand opnieuw om de actuele verschillen te controleren.');const chosen=[...document.querySelectorAll('[data-fin-import]:checked')].map(x=>Number(x.dataset.finImport)),remove=[...document.querySelectorAll('[data-plan-remove]:checked')].map(x=>x.dataset.planRemove);if(!chosen.length&&!remove.length)throw Error('Er zijn geen wijzigingen geselecteerd.');save(FinancePlan.apply(d,state.preview,chosen,remove));state.year=state.preview.year;state.preview=null;state.view='overview';render();showAppNotice('Agenda en begroting bijgewerkt. Een nieuwe download bevat de actuele gegevens.');return;}
 case 'cancel':requireAccess(true);if(!confirm('Deze post laten vervallen en de reservering vrijgeven?'))return;if(e.kind==='series'&&d.finance.entries.some(c=>c.seriesId===e.id&&C.received(c)))throw Error('Deze serie heeft ontvangen losse betalingen. Corrigeer die eerst.');C.cancel(e);save(d);render();return;
 case 'reopen':requireAccess(true);if(e.status==='settled'&&!confirm('Afrekening heropenen? De uitbetaling wordt uit het saldo gehaald en de begroting wordt weer gereserveerd.'))return;e.status='planned';e.payout=0;save(d);render();return;
 case 'participants':requireAccess(true);if(onlyFinance())openPaymentOnly(el.dataset.id);else{nav('invoer');openInvoer(el.dataset.id);}return;
 case 'start-match':requireAccess(true);if(onlyFinance())throw Error('Laat een wedstrijdbeheerder de wedstrijd eerst starten vanuit de agenda.');nav('invoer');maakWedstrijdVanRoosterItem(el.dataset.id);return;
 case 'attachment':{const a=e.attachments[Number(el.dataset.index)];if(!a||!/^data:(image\/(jpeg|png)|application\/pdf);base64,/.test(a.data))throw Error('Ongeldige bijlage.');const bytes=Uint8Array.from(atob(a.data.split(',')[1]),c=>c.charCodeAt(0));triggerBlobDownload(new Blob([bytes],{type:a.type}),a.name);return;}
 case 'remove-attachment':requireAccess(true);if(!confirm('Deze bijlage verwijderen?'))return;e.attachments.splice(Number(el.dataset.index),1);save(d);render();return;
 case 'excel':await excelReport();return;
 case 'pdf':await pdfReport();return;
 case 'backup':requireAccess(true);exporteerBackup();return;
 }
}
function openPaymentOnly(wid){const d=getData(),e=C.matchEntry(d,wid);if(e?.seriesId){state.detail=e.id;state.view='detail';render();return;}page.innerHTML=`${button('← Wedstrijdafrekening','detail',`data-id="${A(e.id)}"`)}<div class="card"><h2>Deelnemers · ${E(e.title)}</h2>${paymentList(e,d,true)}</div>`;}
async function change(el){
 const kind=el.dataset.finChange;
 if(kind==='year'){const y=Number(el.value);if(!Number.isInteger(y)||y<2000||y>2100)throw Error('Kies een jaar tussen 2000 en 2100.');state.year=y;render();return;}
 if(kind==='filter'){state.filter=el.value;render();return;}
 if(kind==='permission'||kind==='finance-only'){if(!isHoofdAdmin())throw Error('Alleen de hoofdbeheerder beheert rechten.');const d=getData(),a=d.admins.find(a=>a.id===el.dataset.id);if(a.rol==='hoofd')return;if(kind==='permission')a.financeAccess=el.value;else a.financeOnly=el.checked;saveData(d);updateAdminUi();return;}
 if(kind==='series-mode'){
 requireAccess(true);const d=getData(),e=d.finance.entries.find(e=>e.id===el.dataset.id);if(!e?.seriesId)throw Error('Serie niet gevonden.');if(!e.members.includes(el.dataset.member))e.members.push(el.dataset.member);C.setSeriesMode(d,e.seriesId,el.dataset.member,el.value);save(d);refreshSeriesPayment(el,e);return;
 }
 if(kind==='paid'&&getData().finance.entries.find(e=>e.id===el.dataset.id)?.seriesId){
 requireAccess(true);const d=getData(),e=d.finance.entries.find(e=>e.id===el.dataset.id),p=C.seriesFor(d,e),id=el.dataset.member,mode=p.enrollments[id];if(!mode||!p.configured||p.status==='cancelled')throw Error('Stel eerst de serie en deelname in.');const target=mode==='series'?p:e;if(!el.checked&&!confirm('Betaling terugzetten naar openstaand?')){el.checked=true;return;}if(!e.members.includes(id))e.members.push(id);if(!p.members.includes(id))p.members.push(id);if(el.checked)target.payments[id]={amount:mode==='series'?p.fee:p.looseFee,date:getVandaagIso()};else delete target.payments[id];save(d);refreshSeriesPayment(el,e);return;
 }
 if(kind==='paid'){
  requireAccess(true);const d=getData(),e=d.finance.entries.find(e=>e.id===el.dataset.id),id=el.dataset.member;if(!e||e.status==='cancelled')throw Error('Deze wedstrijd is niet beschikbaar voor betalingen.');if(!e.configured)throw Error('Vul eerst de financiële wedstrijdgegevens in.');
  if(!el.checked&&e.payments[id]&&!confirm('Ontvangen betaling terugzetten naar openstaand?')){el.checked=true;return;}
  if(el.closest('.fin-pay-panel'))e.members=[...new Set([...e.members,...(invoerState.rows||[]).filter(r=>r.selected&&!r.afwezig).map(r=>r.vid)])];if(!e.members.includes(id))e.members.push(id);if(el.checked)e.payments[id]={amount:e.fee,date:getVandaagIso()};else delete e.payments[id];save(d);if(el.closest('.fin-pay-panel'))mountPayments();else openPaymentOnly(e.matchId);return;
 }
 if(el.dataset.waterField){requireAccess(true);const d=getData(),rowEl=el.closest('[data-water]'),w=FinanceWaters.find(d,rowEl.dataset.water);if(!w)throw Error('Viswater niet gevonden.');const f=el.dataset.waterField,v=el.value.trim();
  if(f==='name'){if(!v)throw Error('Naam mag niet leeg zijn.');if(FinanceWaters.find(d,v)&&FinanceWaters.find(d,v)!==w)throw Error('Dit viswater bestaat al.');w.name=v;}
  else if(['gather','start','end'].includes(f)){if(v&&!/^([01]?\d|2[0-3])[:.][0-5]\d$/.test(v))throw Error('Gebruik een tijd zoals 08:30.');w[f]=v?v.replace('.',':').padStart(5,'0'):'';}
  else w[f]=v;save(d);render();return;}
 if(el.id==='fin-import-file')await readImport(el.files[0]);if(el.id==='fin-attachment-file')await addAttachment(el.files[0]);
}
function submit(form){
 requireAccess(true);const d=getData(),e=currentEntry(d);
 if(form.id==='fin-series-form'){if(e.kind!=='series')throw Error('Geen serie geselecteerd.');Object.assign(e,{planned:C.cents(read('fin-series-planned')),fee:C.cents(read('fin-series-fee')),feeAow:C.cents(read('fin-series-aow')),looseFee:C.cents(read('fin-series-loose')),note:read('fin-series-note'),configured:true,migrationNotice:false});save(d);}
 if(form.id==='fin-water-form'){FinanceWaters.upsert(d,{name:read('fin-water-name'),location:read('fin-water-location')});save(d);}
 if(form.id==='fin-budget-form'){d.finance.years[state.year]={budget:C.cents(read('fin-budget')),carry:C.cents(read('fin-carry')),configured:true};save(d);state.view='overview';}
 if(form.id==='fin-entry-form'){
  const title=read('fin-title').trim();if(!title)throw Error('Vul een omschrijving in.');const date=read('fin-date')?C.date(read('fin-date')):e.kind==='expense'?'':C.date('');e.year=Number(date.slice(0,4)||e.year||state.year);if(e.status==='settled'&&date.slice(0,4)!==e.date.slice(0,4))throw Error('Heropen de post voordat je hem naar een ander jaar verplaatst.');
  Object.assign(e,{title,date,planned:C.cents(read('fin-planned')),note:read('fin-note'),configured:true});if(e.kind==='expense')e.category=read('fin-category').trim()||'Overig';else e.fee=C.cents(read('fin-fee'));
  const r=d.roosterItems.find(r=>r.id===e.agendaId);if(r){r.titel=title;r.datum=date;}for(const wid of C.matchIds(d,e.matchId)){const w=d.wedstrijden.find(w=>w.id===wid);if(w){w.naam=title;w.datum=date;}}save(d);
 }
 if(form.id==='fin-settle-form'){if(e.status==='cancelled')throw Error('Heropen eerst deze post.');e.payout=C.cents(read('fin-payout'));e.status='settled';save(d);}
 if(form.id==='fin-user-form'){if(!isHoofdAdmin())throw Error('Alleen de hoofdbeheerder beheert accounts.');const name=read('fin-user-name').trim(),code=read('fin-user-code').trim();if(!name||code.length<4)throw Error('Vul een naam en een code van minimaal vier tekens in.');d.admins.push({id:uid(),naam:name,code,rol:'admin',actief:true,financeOnly:true,financeAccess:read('fin-user-right')});save(d);if(state.view!=='rights')renderBeheer();}
 render();showAppNotice('Opgeslagen.');
}
document.addEventListener('click',ev=>{const el=ev.target.closest('[data-fin]');if(el){ev.preventDefault();Promise.resolve(action(el.dataset.fin,el)).catch(noticeError);}});
document.addEventListener('change',ev=>{if(ev.target.matches('[data-fin-change],[data-water-field],#fin-import-file,#fin-attachment-file'))Promise.resolve(change(ev.target)).catch(err=>{noticeError(err);if(['paid','series-mode'].includes(ev.target.dataset.finChange)){if(ev.target.closest('.fin-pay-panel'))mountPayments();else render();}});});
document.addEventListener('submit',ev=>{if(ev.target.id.startsWith('fin-')){ev.preventDefault();try{submit(ev.target);}catch(err){noticeError(err);}}});
const originalImport=renderImport;renderImport=function(){originalImport();if(allowed(true))byId('pv-import').insertAdjacentHTML('afterbegin',`<div class="card"><h2>Jaaragenda en begroting</h2><p>Importeer geplande wedstrijden en uitgaven via Financiën.</p>${button('Jaarplanning importeren','import')}</div>`);};
const oldBackupRender=renderBackup;renderBackup=function(){if(!isHoofdAdmin()){showAppNotice('Alleen de hoofdbeheerder beheert volledige back-ups.','warn');return;}oldBackupRender();};
exporteerBackup=function(){if(!isHoofdAdmin()){showAppNotice('Alleen de hoofdbeheerder kan een volledige back-up maken.','warn');return;}const data=getData(),meta=maakBackupMetadata(data);triggerBlobDownload(new Blob([JSON.stringify({meta,data},null,2)],{type:'application/json'}),'HSV_GHW_backup_'+new Date().toISOString().slice(0,10)+'.json');showAppNotice('Back-up inclusief financiën en bijlagen gedownload.');};
const oldRestore=bevestigHerstel;bevestigHerstel=function(){if(!isHoofdAdmin())return;oldRestore();doLogout();};
const oldWipe=wisAlles;wisAlles=function(){if(!isHoofdAdmin())return;oldWipe();};
const oldPlanning=getRoosterPlanningItems;getRoosterPlanningItems=function(d){return oldPlanning(d).map(r=>{const e=d.finance?.entries.find(e=>e.agendaId===r.id);return e?.status==='cancelled'?{...r,titel:'Afgelast · '+r.titel}:r;});};
const oldStart=maakWedstrijdVanRoosterItem;maakWedstrijdVanRoosterItem=function(id){const e=getData().finance.entries.find(e=>e.agendaId===id);if(e?.status==='cancelled'){showAppNotice('Deze wedstrijd is afgelast. Heropen eerst de financiële post.','warn');return;}oldStart(id);};
window.Finance={render,access,allowed,openDetail,state,summary:()=>C.summary(getData(),state.year)};
updateAdminUi();
})();
