const assert=require('node:assert/strict'),C=require('./finance-series.js');
const blank=()=>({admins:[],vissers:[],competities:[],wedstrijden:[],uitslagen:[],roosterItems:[],finance:{years:{2026:{budget:200000}},entries:[]}});
const sr={kind:'series',externalId:'S1',date:'2026-01-01',title:'Winterserie',fee:6000,looseFee:1000,planned:4000};
const rows=[sr,...[1,2].map(n=>({kind:'match',externalId:'W'+n,date:'2026-01-0'+n,title:'Winterserie '+n,form:'serie',series:'Winterserie',number:n,fee:0,planned:0,water:'Binnenmaas'}))];
let d=C.applyImport(blank(),C.previewImport(blank(),rows));let p=d.finance.entries.find(e=>e.kind==='series'),kids=d.finance.entries.filter(e=>e.seriesId);assert.equal(kids.length,2);assert.equal(C.summary(d,2026).reserved,4000);assert.equal(C.summary(d,2026).free,196000);assert.equal(C.previewImport(d,rows).filter(r=>r.action!=='same').length,0);
kids.forEach(k=>k.members=['full','loose']);C.setSeriesMode(d,p.id,'full','series');C.setSeriesMode(d,p.id,'loose','loose');assert.equal(C.summary(d,2026).open,8000);p.payments.full={amount:6000};assert.equal(C.summary(d,2026).free,196000);kids[0].payments.loose={amount:1000};assert.equal(C.summary(d,2026).free,197000);assert.equal(C.summary(d,2026).extra,1000);assert.equal(C.summary(d,2026).held,6000);kids[1].payments.loose={amount:1000};assert.equal(C.summary(d,2026).free,198000);assert.equal(C.received(p)+p.planned,10000);p.payout=10000;p.status='settled';assert.equal(C.summary(d,2026).free,198000);assert.equal(C.summary(d,2026).net,4000);assert.equal(C.summary(d,2026).reserved,0);assert.throws(()=>C.setSeriesMode(d,p.id,'full','loose'));assert.equal(C.previewImport(d,[{...sr,planned:5000}])[0].blocked,true);
assert.throws(()=>C.previewImport(blank(),[{...rows[1],planned:4000}]));
// Legacy per-match funds are preserved and flagged, rather than summing contributions.
d=blank();d.roosterItems=[{id:'old',type:'wedstrijd',wedstrijdVorm:'serie',serieNaam:'Oude serie',datum:'2026-02-01',titel:'Oud'}];C.sync(d);let c=d.finance.entries.find(e=>e.kind==='match');p=C.seriesFor(d,c);c.payments.a={amount:1000};c.members=['a'];C.sync(d);assert.equal(C.summary(d,2026).extra,0);assert.equal(C.summary(d,2026).held,1000);C.setSeriesMode(d,p.id,'a','series');assert.equal(C.received(p),1000);assert.equal(C.received(c),0);assert.equal(C.summary(d,2026).held,1000);
console.log('PASS: one series contribution, full-series payment once, per-match loose receipts as free budget, correct prize fund, settlement, repeat import, blocked tariff overwrites and preserved legacy receipts');
