/* Finance UI for the trusted-device edition of HSV GHW. */
(function(){
'use strict';
const C=FinanceCore;
const state={year:new Date().getFullYear(),detail:null,view:'overview',preview:null,importErrors:null};
const money=n=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format((n||0)/100);
const E=escapeHtml, A=escapeHtmlAttr;
const euroInput=n=>((n||0)/100).toFixed(2);
const byId=id=>document.getElementById(id);
const read=id=>byId(id)?.value??'';
const button=(label,action,extra='',cls='btn btn-gh')=>`<button type="button" class="${cls}" data-fin="${action}" ${extra}>${label}</button>`;
const input=(id,label,value='',type='text',extra='')=>`<label class="fin-field"><span>${label}</span><input id="${id}" type="${type}" value="${A(value)}" ${extra}></label>`;
const amount=(id,label,value=0)=>input(id,label,euroInput(value),'number','min="0" max="10000000" step="0.01" inputmode="decimal" required');
function profile(){return isAdmin&&currentAdmin?getData().admins.find(a=>a.id===currentAdmin.id&&a.actief!==false):null;}
function access(){const a=profile();return a?.rol==='hoofd'?'write':a?.financeAccess||'none';}
function allowed(edit=false){return edit?access()==='write':['read','write'].includes(access());}
function requireAccess(edit=false){if(!allowed(edit))throw Error(edit?'Je hebt geen financiële bewerkrechten.':'Je hebt geen toegang tot de financiële administratie.');}
function onlyFinance(){return !!profile()?.financeOnly;}
function currentEntry(d){return d.finance.entries.find(e=>e.id===state.detail);}
function save(d){requireAccess(true);saveData(d);}
function noticeError(err){showAppNotice(err.message||String(err),'warn',6500);}
const oldNormalize=ensureAdminData;
ensureAdminData=function(d){const permissions=new Map((d.admins||[]).map(a=>[a.id,{financeAccess:a.financeAccess,financeOnly:a.financeOnly}]));const out=oldNormalize(d);for(const a of out.admins){const p=permissions.get(a.id)||{};a.financeAccess=['none','read','write'].includes(p.financeAccess)?p.financeAccess:'none';a.financeOnly=p.financeOnly===true&&a.rol!=='hoofd';}C.sync(out);return out;};
const oldSave=saveData;
saveData=function(d){try{return oldSave(d);}catch(e){if(e.name==='QuotaExceededError')showAppNotice('Opslaan mislukt: de browseropslag is vol. Maak een back-up en verklein of verwijder bijlagen.','warn',10000);throw e;}};
const page=document.createElement('div');page.className='pv';page.id='pv-finance';byId('pv-admin-home').parentNode.appendChild(page);
const navButton=document.createElement('button');navButton.id='nav-finance';navButton.className='sb-btn';navButton.textContent='Financiën';navButton.style.display='none';navButton.onclick=()=>nav('finance');byId('admin-nav').after(navButton);
titles.finance='Financiën';ADMIN_PAGES.push('finance');
const oldNav=nav;
nav=function(p,...args){if(p==='finance'&&!allowed()){if(!isAdmin)openPin();else showAppNotice('Geen toegang tot financiën.','warn');return;}if(onlyFinance()&&ADMIN_PAGES.includes(p)&&!['finance','admin-home'].includes(p)){showAppNotice('Dit account heeft alleen financiële toegang.','warn');return;}if(p==='backup'&&!isHoofdAdmin()){showAppNotice('Volledige back-ups zijn alleen voor de hoofdbeheerder.','warn');return;}oldNav(p,...args);if(p==='finance')render();};
const oldAdminUi=updateAdminUi;
updateAdminUi=function(){oldAdminUi();navButton.style.display=allowed()?'flex':'none';if(onlyFinance())byId('admin-nav').style.display='none';byId('nav-backup').style.display=isHoofdAdmin()?'flex':'none';if(!allowed()){page.innerHTML='';document.querySelectorAll('.fin-pay-panel').forEach(el=>el.remove());}};
const oldHome=renderAdminHome;
renderAdminHome=function(){if(onlyFinance()){byId('admin-home-content').innerHTML=`<div class="card"><div class="stitle">Welkom ${E(currentAdmin.naam)}</div><p>Jouw toegang: ${access()==='write'?'begroting bekijken en bewerken':'begroting bekijken'}.</p>${button('Open financiën','open','','btn btn-g')}</div>`;return;}oldHome();const today=todayMatches(getData());byId('admin-home-content').insertAdjacentHTML('afterbegin',`<div class="card fin-home"><div><div class="stitle">Wedstrijd van vandaag</div><div class="sub">${today.length?E(today.map(m=>m.title).join(' · ')):'Vandaag staat er geen wedstrijd in de agenda.'}</div></div>${today.length?button(today.length>1?'Kies wedstrijd':'Naar de invoer','today','','btn btn-g'):''}</div><div id="fin-today-list" class="fin-toolbar"></div>`+(allowed()?`<div class="card fin-home"><div><div class="stitle">Financiën</div><div class="sub">Begroting, werkelijke kosten en wie nog moet betalen.</div></div>${button('Open financiën','open','','btn btn-g')}</div>`:''));};
const oldLogout=doLogout;
doLogout=function(){state.detail=null;state.preview=null;oldLogout();page.innerHTML='';};
const oldAccounts=renderAdminGegevensPane;
renderAdminGegevensPane=function(){return oldAccounts()+(isHoofdAdmin()?permissionsHtml():'');};
function permissionsHtml(){return `<div class="card"><div class="stitle">Toegang tot financiën</div><p class="sub">De hoofdbeheerder kan altijd bewerken. Je kunt andere gebruikers toegang geven tot alleen financiën.</p>${getData().admins.map(a=>`<div class="fin-permission"><strong>${E(a.naam)}</strong>${a.rol==='hoofd'?'<span>Hoofdbeheerder · bewerken</span>':`<label>Financiën<select data-fin-change="permission" data-id="${A(a.id)}"><option value="none" ${a.financeAccess==='none'?'selected':''}>Geen toegang</option><option value="read" ${a.financeAccess==='read'?'selected':''}>Alleen kijken</option><option value="write" ${a.financeAccess==='write'?'selected':''}>Kijken en bewerken</option></select></label><label><input type="checkbox" data-fin-change="finance-only" data-id="${A(a.id)}" ${a.financeOnly?'checked':''}> Alleen financiën, geen uitslagenbeheer</label>`}</div>`).join('')}<form id="fin-user-form"><h3>Financiële gebruiker toevoegen</h3><div class="fin-fields">${input('fin-user-name','Naam','','text','required')}${input('fin-user-code','Persoonlijke code','','password','required minlength="4" autocomplete="new-password"')}<label class="fin-field"><span>Rechten</span><select id="fin-user-right"><option value="read">Alleen kijken</option><option value="write">Kijken en bewerken</option></select></label></div><button class="btn btn-g" type="submit">Gebruiker toevoegen</button></form></div>`;}
const formLabel={solo:'Individueel',koppel:'Koppel',gescheiden_koppel:'Gescheiden koppel',serie:'Serie'};
const nameOf=(d,id)=>{const v=(d.vissers||[]).find(v=>v.id===id);return v?vNaam(v):'Verwijderde visser';};
const unitLabel=(d,u)=>u.members.map(id=>nameOf(d,id)).join(' & ');
const yearEntries=d=>d.finance.entries.filter(e=>String(e.date||e.year).slice(0,4)===String(state.year));
function agendaOf(d,e){const a=(d.roosterItems||[]).find(a=>a.id===e.agendaId)||{},w=(d.wedstrijden||[]).find(w=>w.id===e.matchId)||{};return {form:a.wedstrijdVorm||(w.gescheidenGroepId?'gescheiden_koppel':w.isKoppel?'koppel':'solo'),water:a.water||w.water||'',location:a.locatie||w.locatie||'',gather:a.verzamelen||'',start:a.starttijd||'',end:a.eindtijd||'',rod:a.hengeltype||'',endDate:a.einddatum||''};}
function agendaLine(d,e){if(e.kind!=='match')return e.kind==='series'?'Serie':'Overige uitgave';const a=agendaOf(d,e),p=C.seriesFor(d,e);return [p?'Serie '+p.title:formLabel[a.form],a.water,a.location,[a.gather,a.start,a.end].filter(Boolean).join(' / '),a.rod].filter(Boolean).join(' · ');}
function actualOf(e){return C.spent(getData(),e);}
function overview(){
 const d=getData(),s=C.summary(d,state.year),write=allowed(true),items=C.open(d,state.year);
 const list=yearEntries(d).filter(e=>!e.seriesId&&e.status!=='cancelled').sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999')||a.title.localeCompare(b.title));
 const openFor=e=>items.filter(i=>i.entryId===e.id||(e.kind==='series'&&d.finance.entries.some(c=>c.seriesId===e.id&&c.id===i.entryId)));
 return `<div class="fin-heading"><div><span class="fin-eyebrow">CONCOURSBEGROTING</span><h1>Begroting ${state.year}</h1></div><label class="fin-year">Kalenderjaar<input id="fin-year" type="number" min="2000" max="2100" value="${state.year}" data-fin-change="year"></label></div>
 <div class="card fin-result ${s.over<0?'fin-negative':'fin-available'}"><div class="fin-result-head"><span class="fin-eyebrow">RESULTAAT ${state.year}</span><strong>${s.over<0?'− ':'+ '}${money(Math.abs(s.over))}</strong><small>${s.over<0?'tekort':'over'} · heel jaar, alles wat nog komt telt als begroot</small></div><table class="fin-staat"><tbody><tr><td>+</td><td>Begroting vereniging</td><td>${money(s.budget+s.carry)}</td></tr>${s.extras?`<tr><td>+</td><td>Extra bijdrage</td><td>${money(s.extras)}</td></tr>`:''}<tr><td>+</td><td>Inleg vissers</td><td>${money(s.inleg-s.loose)}</td></tr><tr><td>+</td><td>Losse inleg series</td><td>${money(s.loose)}</td></tr><tr><td>−</td><td>Uitgaven · prijzengeld en kosten</td><td>${money(s.spent)}</td></tr><tr class="fin-staat-total"><td>=</td><td>Resultaat ${state.year}</td><td>${money(s.over)}</td></tr></tbody></table><p class="fin-staat-foot">Begroot t/m vandaag <b>${money(s.plannedToDate)}</b> · heel jaar <b>${money(s.planned)}</b>${s.extras?'':' · '+'<a href="#" data-fin="budget">extra bijdrage toevoegen</a>'}</p></div>
 ${s.missing?`<div class="info">${s.missing} post(en) hebben nog geen begroot bedrag; die tellen nog niet mee.</div>`:''}${!s.start&&write?'<div class="info">Vul de begroting in via <b>Begroting instellen</b> of cel D2 van de jaarplanning.</div>':''}
 ${items.length?openCard(d,items,write):''}
 <div class="fin-toolbar">${write?button('Begroting instellen','budget')+button('+ Overige uitgave','new','','btn btn-g')+button('Jaarplanning downloaden','template')+button('Jaarplanning uploaden','import')+button('Viswateren','waters')+button('Dubbele wedstrijden','duplicates'):''}${isHoofdAdmin()?button('Back-up downloaden','backup')+button('Toegangsrechten','rights'):''}</div>
 <div class="card fin-ledger"><div class="fin-list-heading"><h2>Wedstrijden en uitgaven</h2><span>${list.length} posten</span></div><div class="fin-table-head"><span>Post / datum</span><span>Inleg</span><span>Begroot</span><span>Uitgegeven</span></div>${list.length?list.map(e=>{const o=openFor(e),act=actualOf(e);return `<button class="fin-row" data-fin="detail" data-id="${A(e.id)}"><span class="fin-post"><strong>${E(e.title)}</strong><small>${E(e.date?nlDatum(e.date):'Geen datum')} · ${E(agendaLine(d,e))}</small></span><span><small class="fin-mobile-label">Inleg</small>${e.kind==='expense'?'—':money(C.inleg(d,e))}${o.length?` <span class="fin-badge open">${o.length} open</span>`:''}</span><span><small class="fin-mobile-label">Begroot</small>${e.configured?money(e.planned):'<em>Nog invullen</em>'}</span><span><small class="fin-mobile-label">Uitgegeven</small>${e.configured?(e.actual!==null?'<b>'+money(act)+'</b>':money(act)):'—'}</span></button>`;}).join(''):'<div class="fin-empty">Nog geen posten. Upload een jaarplanning of voeg een uitgave toe.</div>'}</div>
 ${yearEntries(d).some(e=>e.status==='cancelled')?`<p class="fin-footnote">Vervallen posten worden niet getoond en tellen niet mee.</p>`:''}`;
}
function openCard(d,items,write){
 const money0=n=>money(n||0);const choices=new Map();for(const i of items.filter(i=>i.kind==='choice'))choices.set(i.entryId,(choices.get(i.entryId)||0)+1);
 const choiceRows=[...choices.entries()].map(([id,n])=>`<div class="fin-payment"><span><strong>${E(d.finance.entries.find(e=>e.id===id)?.title||'Serie')}</strong><small>${n} visser(s) nog <em>serie of los</em> kiezen</small></span>${button('Kiezen','detail',`data-id="${A(id)}"`)}</div>`).join('');
 const rows=choiceRows+items.filter(i=>i.kind!=='choice').map(i=>`<div class="fin-payment"><span><strong>${E(unitLabel(d,i.unit))}</strong><small>${E(i.title)}${i.date&&i.kind!=='series'?' · '+E(nlDatum(i.date)):''} · ${i.kind==='series'?'serietarief '+money0(i.amount):money0(i.amount)}</small></span>${write?button('Alsnog betaald','settle-open',`data-entry="${A(i.entryId)}" data-unit="${A(i.unit.id)}" data-kind="${i.kind}"`,'btn btn-g btn-sm'):''}</div>`).join('');
 const total=items.reduce((s,i)=>s+(i.amount||0),0);
 return `<div class="card fin-open"><div class="fin-list-heading"><h2>Nog niet betaald</h2><span>${items.filter(i=>i.kind!=='choice').length} · ${money(total)}</span></div>${rows}</div>`;
}
function budgetHtml(){const y=getData().finance.years[state.year]||{},extras=[...(y.extras||[]),{title:'',amount:0}];return `${back()}<div class="card"><h2>Begroting ${state.year}</h2><p class="sub">Het totaal dat de vereniging voor het concours beschikbaar stelt, eventueel plus wat uit het vorige jaar is overgebleven.</p><form id="fin-budget-form"><div class="fin-fields">${amount('fin-budget','Begroting',y.budget)}${amount('fin-carry','Meegenomen uit vorig jaar',y.carry)}</div><h3>Extra bijdragen</h3><p class="sub">Bijvoorbeeld een extra bijdrage van de vereniging of een sponsor. Een lege regel wordt overgeslagen.</p>${extras.map((x,i)=>`<div class="fin-fields fin-extra-row"><label class="fin-field"><span>Omschrijving</span><input data-extra-title value="${A(x.title)}" placeholder="Extra bijdrage vereniging"></label><label class="fin-field"><span>Bedrag</span><input data-extra-amount type="number" min="0" step="0.01" inputmode="decimal" value="${euroInput(x.amount)}"></label></div>`).join('')}<button class="btn btn-g">Opslaan</button></form></div>`;}
function back(){return button('← Begroting','back','', 'btn btn-gh fin-back');}
function amountsForm(e,write){const isSeries=e.kind==='series',isMatch=e.kind==='match';return `<form id="fin-entry-form"><fieldset ${write?'':'disabled'}><div class="fin-fields">${input('fin-title',isSeries?'Serienaam':'Omschrijving',e.title,'text','required')}${isMatch||e.kind==='expense'?input('fin-date','Datum',e.date,'date',isMatch?'required':''):''}${amount('fin-planned',isSeries?'Begroot · bijdrage hele serie':isMatch?'Begroot · bijdrage vereniging':'Begroot',e.planned)}${amount('fin-actual',isSeries||isMatch?'Uitbetaald prijzengeld (vooringevuld: prijzenpot)':'Uitgegeven (vooringevuld: begroot)',actualOf(e))}${isMatch&&!e.seriesId?amount('fin-fee','Inleg '+(e.feeBasis==='koppel'?'per koppel':'per persoon'),e.fee)+(agendaOf(getData(),e).form!=='solo'?`<label class="fin-field"><span>Inleg rekenen</span><select id="fin-fee-basis"><option value="koppel" ${e.feeBasis==='koppel'?'selected':''}>per koppel</option><option value="person" ${e.feeBasis!=='koppel'?'selected':''}>per persoon</option></select></label>`:''):''}${isSeries?amount('fin-series-loose','Inleg los',e.looseFee)+amount('fin-series-loose-aow','Inleg los · AOW',e.looseFeeAow||0)+amount('fin-series-fee','Inleg hele serie',e.fee)+amount('fin-series-aow','Inleg hele serie · AOW',e.feeAow||0):''}</div>${write?'<button class="btn btn-g" type="submit">Opslaan</button>':''}</fieldset></form>`;}
function participantsHtml(d,e,editable){
 const units=C.units(d,e),p=C.seriesFor(d,e);
 if(!units.length)return '<p class="sub">De deelnemers verschijnen zodra de uitslag is ingevoerd.</p>';
 return `<div class="fin-payment-list">${units.map(u=>{const vid=u.members[0],mode=p?p.enrollments[vid]||'':'',a=C.amount(d,e,u),unpaid=Object.prototype.hasOwnProperty.call(e.unpaid,u.id),aow=u.members.some(id=>C.isAow(d,id)),seriesPaid=p&&mode==='series'?Object.prototype.hasOwnProperty.call(p.seriesPaid,vid):false;
  const status=a===null?'<em class="fin-error-text">kies serie of los</em>':mode==='series'?(seriesPaid?'serie betaald':'serietarief '+money(C.seriesAmount(d,p,vid))+' <b>open</b>'):unpaid?money(a)+' <b>open</b>':a?money(a)+' betaald':'—';
  const controls=!editable?'':p?`<select data-fin-change="series-mode" data-id="${A(p.id)}" data-member="${A(vid)}" class="${mode?'':'fin-choose'}"><option value="">Kies…</option><option value="series" ${mode==='series'?'selected':''}>Serie</option><option value="loose" ${mode==='loose'?'selected':''}>Los</option></select>${mode==='series'?`<label><input type="checkbox" data-fin-change="series-paid" data-id="${A(p.id)}" data-member="${A(vid)}" ${seriesPaid?'checked':''}> Serie betaald</label>`:mode==='loose'?`<label><input type="checkbox" data-fin-change="unpaid" data-id="${A(e.id)}" data-unit="${A(u.id)}" ${unpaid?'checked':''}> Nog niet betaald</label>`:''}`:`<label><input type="checkbox" data-fin-change="unpaid" data-id="${A(e.id)}" data-unit="${A(u.id)}" ${unpaid?'checked':''}> Nog niet betaald</label>`;
  return `<div class="fin-payment fin-series-person"><span><strong>${E(unitLabel(d,u))}${aow?' <span class="fin-badge">AOW</span>':''}</strong><small>${status}</small></span>${controls}</div>`;}).join('')}</div>`;
}
function looseCard(d,p){const rows=C.looseIncome(d,p);if(!rows.length)return '';const total=rows.reduce((s,r)=>s+r.total,0);return `<div class="card"><div class="fin-list-heading"><h2>Losse inleg · extra inkomsten</h2><span>${money(total)}</span></div><p class="sub">Losse deelnemers betalen per wedstrijd; dit geld komt extra in kas en telt mee in <b>Over</b>.</p>${rows.map(r=>`<div class="fin-payment"><span><strong>${E(nameOf(d,r.vid))}</strong><small>${r.count} wedstrijd${r.count===1?'':'en'} los</small></span><span>${money(r.total)}</span></div>`).join('')}</div>`;}
function seriesMembersHtml(d,p,editable){const ids=[...new Set(p.members||[])].sort((a,b)=>nameOf(d,a).localeCompare(nameOf(d,b),'nl'));if(!ids.length)return '<p class="sub">Nog geen deelnemers; die verschijnen na de eerste uitslag.</p>';
 return `<div class="fin-payment-list">${ids.map(vid=>{const mode=p.enrollments[vid]||'',paid=Object.prototype.hasOwnProperty.call(p.seriesPaid,vid),aow=C.isAow(d,vid);const status=!mode?'<em class="fin-error-text">kies serie of los</em>':mode==='series'?(paid?'serie betaald':'serietarief '+money(C.seriesAmount(d,p,vid))+' <b>open</b>'):'los · per wedstrijd';
  const controls=!editable?'':`<select data-fin-change="series-mode" data-id="${A(p.id)}" data-member="${A(vid)}" class="${mode?'':'fin-choose'}"><option value="">Kies…</option><option value="series" ${mode==='series'?'selected':''}>Serie</option><option value="loose" ${mode==='loose'?'selected':''}>Los</option></select>${mode==='series'?`<label><input type="checkbox" data-fin-change="series-paid" data-id="${A(p.id)}" data-member="${A(vid)}" ${paid?'checked':''}> Serie betaald</label>`:''}`;
  return `<div class="fin-payment fin-series-person"><span><strong>${E(nameOf(d,vid))}${aow?' <span class="fin-badge">AOW</span>':''}</strong><small>${status}</small></span>${controls}</div>`;}).join('')}</div>`;}
function moneyLine(d,e){if(e.kind==='expense'||!e.configured)return '';const i=C.inleg(d,e),p=C.pot(d,e),sp=C.spent(d,e);return `<div class="fin-summary fin-summary-small"><div><span>Inleg</span><strong>${money(i)}</strong></div><div><span>Begroot</span><strong>${money(e.planned)}</strong></div><div><span>Prijzenpot</span><strong>${money(p)}</strong></div><div><span>Uitbetaald</span><strong>${money(sp)}</strong></div><div class="${p-sp<0?'fin-negative':'fin-available'}"><span>Verschil</span><strong>${money(p-sp)}</strong></div></div>`;}
function detailHtml(){
 const d=getData(),e=currentEntry(d);if(!e){state.view='overview';return overview();}const write=allowed(true);
 if(e.kind==='series'){const children=d.finance.entries.filter(c=>c.seriesId===e.id).sort((a,b)=>a.date.localeCompare(b.date));return `${back()}<div class="card"><span class="fin-eyebrow">SERIE</span><h1>${E(e.title)}</h1>${moneyLine(d,e)}${amountsForm(e,write)}</div><div class="card"><div class="fin-list-heading"><h2>Deelnemers</h2><span>${e.members.length}</span></div><p class="sub">Kies per visser serie of los. Een seriedeelnemer staat open tot je <b>Serie betaald</b> aanvinkt; losse deelnemers markeer je per wedstrijd.</p>${seriesMembersHtml(d,e,write)}</div>${looseCard(d,e)}<div class="card"><h2>Wedstrijden</h2>${children.map(c=>`<div class="fin-payment"><span><strong>${E(c.title)}</strong><small>${E(nlDatum(c.date))} · ${E(agendaLine(d,c).replace(/^Serie [^·]*·\s*/,''))}</small></span>${button('Openen','detail',`data-id="${A(c.id)}"`)}</div>`).join('')||'<p class="sub">Nog geen wedstrijden in deze serie.</p>'}</div>${write&&e.status==='planned'?`<div class="fin-toolbar">${button('Serie laten vervallen','cancel')}</div>`:''}`;}
 const p=C.seriesFor(d,e),a=e.kind==='match'?agendaOf(d,e):null;
 return `${p?button('← '+E(p.title),'detail',`data-id="${A(p.id)}"`,'btn btn-gh fin-back'):back()}<div class="card"><span class="fin-eyebrow">${e.kind==='match'?'WEDSTRIJD':'OVERIGE UITGAVE'}</span><h1>${E(e.title)}</h1>${a?`<p class="sub">${E([e.date?nlDatum(e.date):'',formLabel[a.form],a.water,a.location].filter(Boolean).join(' · '))}${a.gather||a.start||a.end?'<br>Loting '+E(a.gather||'—')+' · start '+E(a.start||'—')+' · einde '+E(a.end||'—'):''}${a.rod?' · '+E(a.rod):''}</p>`:''}${p?`<p class="sub">Tarieven van de serie: los ${money(p.looseFee)} (AOW ${money(p.looseFeeAow)}), hele serie ${money(p.fee)} (AOW ${money(p.feeAow)}). Inleg deze wedstrijd (los): ${money(C.inleg(d,e))}. Begroot en uitbetaald staan bij de serie.</p>`:moneyLine(d,e)+amountsForm(e,write)}</div>
 ${e.kind==='match'?`<div class="card"><div class="fin-list-heading"><h2>Deelnemers</h2>${write?(e.matchId?button('Open wedstrijdinvoer','participants',`data-id="${A(e.matchId)}"`):e.agendaId?button('Wedstrijdinvoer starten','start-match',`data-id="${A(e.agendaId)}"`):''):''}</div><p class="sub">Iedereen in de uitslag telt als betaald. Markeer alleen wie nog moet betalen${p?'; kies bij een serie eerst serie of los':''}.</p>${participantsHtml(d,e,write)}</div>`:''}
 ${write&&e.status==='planned'?`<div class="fin-toolbar">${button(e.kind==='match'?'Wedstrijd laten vervallen':'Uitgave laten vervallen','cancel')}</div>`:''}`;
}
function mountPayments(){
 document.querySelectorAll('.fin-pay-panel').forEach(el=>el.remove());if(!isAdmin||!invoerState?.wId)return;
 const d=getData(),e=C.matchEntry(d,invoerState.wId);if(!e||e.status==='cancelled')return;
 const p=C.seriesFor(d,e),el=document.createElement('section');el.className='card fin-pay-panel';
 el.innerHTML=`<div class="fin-list-heading"><h2>Inschrijfgeld</h2><span>${p?'serie · los '+money(p.looseFee)+' / hele serie '+money(p.fee):money(e.fee)+(e.feeBasis==='koppel'?' per koppel':' per persoon')}</span></div><p class="sub">Iedereen telt als betaald. ${p?'Kies per visser serie of los; markeer wie nog moet betalen.':'Markeer alleen wie nog niet betaald heeft.'}</p>${participantsHtml(d,e,true)}`;
 byId('invoer-form')?.appendChild(el);
}
const oldInvoer=renderInvoerForm;
renderInvoerForm=function(){oldInvoer();mountPayments();};
function todayMatches(d){const today=getVandaagIso();const agenda=(d.roosterItems||[]).filter(r=>r.type==='wedstrijd'&&r.datum===today&&r.zichtbaar!==false&&d.finance.entries.find(e=>e.agendaId===r.id)?.status!=='cancelled');const started=(d.wedstrijden||[]).filter(w=>w.datum===today&&!agenda.some(r=>r.gekoppeldeWedstrijdId===w.id));return [...agenda.map(r=>({id:r.id,title:r.titel||r.serieNaam,agenda:true,matchId:r.gekoppeldeWedstrijdId})),...started.map(w=>({id:w.id,title:w.naam,agenda:false,matchId:w.id}))];}
function openToday(item){if(item.matchId){nav('invoer');openInvoer(item.matchId);}else maakWedstrijdVanRoosterItem(item.id);}
function render(){if(!allowed()){page.innerHTML='';return;}page.innerHTML=state.view==='detail'?detailHtml():state.view==='duplicates'?duplicatesHtml():state.view==='budget'?budgetHtml():state.view==='import'?importHtml():state.view==='waters'?watersHtml():state.view==='rights'&&isHoofdAdmin()?back()+permissionsHtml():overview();document.querySelector('.page').scrollTop=0;}
function openDetail(id){requireAccess();state.detail=id;state.view='detail';nav('finance');}
function newExpense(){requireAccess(true);const d=getData(),id='expense-'+uid();d.finance.entries.push({id,kind:'expense',title:'Nieuwe uitgave',date:'',year:state.year,category:'Overig',planned:0,actual:null,status:'planned',configured:false,unpaid:{},members:[]});save(d);openDetail(id);}
function duplicatesHtml(){const pairs=FinancePlan.duplicates(getData(),state.year);return back()+'<div class="card"><h2>Mogelijk dubbele wedstrijden · '+state.year+'</h2><p>Deze regels staan op dezelfde datum, maar zijn nog niet gekoppeld. Kies per paar of ze dezelfde wedstrijd zijn. Er wordt niets automatisch samengevoegd.</p><p class="sub">Bij koppelen blijven uitslagen, betalingen en bonnen behouden. Bij een afwijkende wedstrijdvorm gebruik je de uitslag als basis, zodat de deelnemersindeling behouden blijft.</p></div>'+pairs.map(p=>'<div class="card"><h3>'+E(nlDatum(p.date))+'</h3><p><strong>Agenda:</strong> '+E(p.agendaTitle)+' · '+E(p.agendaForm)+'</p><p><strong>Uitslagen:</strong> '+E(p.resultTitle)+' · '+E(p.resultForm)+'</p><div class="fin-toolbar">'+button('Koppelen · agenda als basis','resolve-duplicate','data-key="'+A(p.key)+'" data-choice="agenda" '+(p.agendaForm!==p.resultForm?'disabled':''))+button('Koppelen · uitslag als basis','resolve-duplicate','data-key="'+A(p.key)+'" data-choice="result"')+button('Apart houden','resolve-duplicate','data-key="'+A(p.key)+'" data-choice="separate"')+'</div></div>').join('')+(!pairs.length?'<div class="card"><p>Geen onbeoordeelde dubbele paren gevonden. Je kunt de bijgewerkte jaarplanning downloaden.</p>'+button('Jaarplanning downloaden','template')+'</div>':'');}
function importHtml(){const p=state.preview,err=state.importErrors;const labels={title:'Naam',date:'Datum',endDate:'Einddatum',form:'Vorm',series:'Serie',rod:'Hengeltype',water:'Viswater',location:'Locatie loting',gather:'Lotingtijd',start:'Starttijd',end:'Eindtijd',planned:'Begroot',fee:'Inleg los / per wedstrijd',seriesFee:'Inleg hele serie',seriesFeeAow:'Inleg hele serie AOW',looseFeeAow:'Inleg los AOW',actual:'Uitbetaald / uitgegeven',feeBasis:'Inleg rekenen'};const val=(k,v)=>v===null||v===undefined||v===''?'—':k==='feeBasis'?(v==='koppel'?'per koppel':'per persoon'):['planned','fee','seriesFee','seriesFeeAow','looseFeeAow','actual'].includes(k)?money(v):k==='form'?(FinancePlan.forms[v]||v):String(v);
 const warnings=w=>w?.length?'<div class="fin-warnings"><strong>Overgeslagen</strong>'+w.map(t=>'<small>'+E(t)+'</small>').join('')+'</div>':'';
 let html=back()+'<div class="card"><h2>Jaarplanning · '+state.year+'</h2><p>Download de planning, vul aan en upload het bestand terug. Eén blad vult agenda én begroting; het blad Viswateren vult lotingplek en tijden automatisch aan.</p><p class="sub">Verplicht per regel: Vorm, Datum en een naam. Alles anders mag leeg (“nog invullen”). Bij een serie zet je de bedragen op één willekeurige regel. Bestaande betalingen, uitslagen en bonnen blijven bewaard.</p><div class="fin-toolbar">'+button('Jaarplanning downloaden','template')+button('Viswateren beheren','waters')+'</div><label class="fin-field"><span>Ingevulde jaarplanning uploaden (.xlsx)</span><input type="file" id="fin-import-file" accept=".xlsx"></label></div>';
 if(err)html+='<div class="card fin-errors"><h2>'+E(err.message)+'</h2><p class="sub">Verbeter de regels in Excel en upload opnieuw. Er is niets gewijzigd.</p><table><thead><tr><th>Blad</th><th>Rij</th><th>Kolom</th><th>Melding</th></tr></thead><tbody>'+err.errors.map(x=>'<tr><td>'+E(x.sheet||'')+'</td><td>'+x.line+'</td><td>'+E(x.column||'')+'</td><td>'+E(x.message)+'</td></tr>').join('')+'</tbody></table>'+warnings(err.warnings)+'</div>';
 if(p){const status={new:'Nieuw',same:'Ongewijzigd',update:'Gewijzigd',error:'Nog oplossen'};
  html+='<div class="card"><h2>Controleer de verschillen</h2><p>Jaar '+p.year+'. Kies welke wijzigingen je wilt overnemen. Wijzigingen binnen één serie worden samen verwerkt.</p>'+warnings(p.warnings)
  +(p.budget.length?'<div class="fin-import-row"><input type="checkbox" checked disabled><span><strong>Jaarbudget '+p.year+'</strong>'+p.budget.map(b=>'<small>'+E(b.label)+': '+money(b.before)+' → '+money(b.after)+'</small>').join('')+'</span></div>':'')
  +p.items.map(x=>'<div class="fin-import-row'+(x.error?' error':'')+'"><input type="checkbox" data-fin-import="'+x.row.line+'" '+(x.action==='same'||x.error?'disabled':'checked')+'><span><strong>'+E(x.row.title||x.row.series)+'</strong><small>Rij '+x.row.line+' · '+E(x.row.date?nlDatum(x.row.date):'Datum nog onbekend')+' · '+status[x.action]+'</small>'+(x.error?'<small class="fin-error-text">'+E(x.error)+'</small>':'')+x.changes.map(c=>'<small>'+labels[c.key]+': '+E(val(c.key,c.before))+' → '+E(val(c.key,c.after))+'</small>').join('')+(x.candidates?.length?'<label class="fin-field"><span>'+(x.error?'Koppel aan een bestaande post of vul een datum in Excel in.':'Is dit een nieuwe post of een gewijzigde bestaande post?')+'</span><select data-plan-map="'+x.row.line+'"><option value="?">Kies een koppeling</option>'+(x.error?'':'<option value="">Nieuwe post</option>')+x.candidates.map(e=>'<option value="'+A(e.id)+'">'+E(e.title+' · '+(e.date?nlDatum(e.date):'Geen datum'))+'</option>').join('')+'</select></label>':'')+'</span></div>').join('')
  +(p.waters.some(w=>w.action!=='same')?'<h3>Viswateren</h3>'+p.waters.filter(w=>w.action!=='same').map(w=>'<div class="fin-import-row"><input type="checkbox" checked disabled><span><strong>'+E(w.name)+'</strong><small>'+(w.action==='new'?'Nieuw':'Gewijzigd')+' · '+E([w.location,w.gather,w.start,w.end].filter(Boolean).join(' · ')||'geen standaardwaarden')+'</small></span></div>').join(''):'')
  +(p.missing.length?'<h3>Ontbreekt in nieuwe upload</h3><p>Deze posten blijven behouden, tenzij je hieronder aangeeft dat ze vervallen.</p>'+p.missing.map(e=>'<label class="fin-import-row"><input type="checkbox" data-plan-remove="'+A(e.id)+'"><span>'+E(e.title)+'<small>'+E(e.date?nlDatum(e.date):'Geen datum')+' · Laten vervallen en reservering vrijgeven</small></span></label>').join(''):'')
  +'<div class="fin-toolbar">'+button('Geselecteerde wijzigingen overnemen','apply-import','','btn btn-g')+button('Annuleren','clear-import')+'</div></div>';}
 return html;}
function watersHtml(){const d=getData(),waters=FinanceWaters.list(d),w=allowed(true);return back()+'<div class="card"><h2>Viswateren</h2><p>Per viswater één lotingplek en vaste tijden. Laat je die velden in de jaarplanning leeg, dan vult de upload ze hieruit aan. De tabel is voorgevuld uit je bestaande agenda; corrigeer wat niet klopt.</p>'+(waters.length?'<div class="fin-table-head fin-waters-head"><span>Viswater</span><span>Locatie loting</span><span>Loting</span><span>Start</span><span>Einde</span><span></span></div>'+waters.map(x=>'<div class="fin-water-row" data-water="'+A(x.name)+'"><input value="'+A(x.name)+'" data-water-field="name" '+(w?'':'disabled')+'><input value="'+A(x.location)+'" data-water-field="location" placeholder="Nog invullen" '+(w?'':'disabled')+'><input value="'+A(x.gather)+'" data-water-field="gather" placeholder="uu:mm" '+(w?'':'disabled')+'><input value="'+A(x.start)+'" data-water-field="start" placeholder="uu:mm" '+(w?'':'disabled')+'><input value="'+A(x.end)+'" data-water-field="end" placeholder="uu:mm" '+(w?'':'disabled')+'>'+(w?button('Verwijderen','remove-water','data-name="'+A(x.name)+'"'):'')+'</div>').join(''):'<p class="sub">Nog geen viswateren. Voeg er een toe of upload een jaarplanning met het blad Viswateren.</p>')+(w?'<form id="fin-water-form" class="fin-fields">'+input('fin-water-name','Nieuw viswater','','text','required')+input('fin-water-location','Locatie loting')+'<button class="btn btn-g">Toevoegen</button></form>':'')+'</div>';}
let importSequence=0;
async function readImport(file){requireAccess(true);const seq=++importSequence;state.preview=null;state.importErrors=null;if(!file)return;try{if(file.size>8*1024*1024)throw Error('Het bestand is te groot (maximaal 8 MB).');const wb=new ExcelJS.Workbook();await wb.xlsx.load(await file.arrayBuffer());if(seq!==importSequence)return;requireAccess(true);const plan=FinancePlan.read(wb);if(plan.rows.length>1000)throw Error('Maximaal 1000 posten per upload.');state.preview=FinancePlan.preview(getData(),plan);state.planSnapshot=localStorage.getItem(SK);render();}catch(e){if(seq===importSequence){state.preview=null;if(e.errors){state.importErrors={message:e.message,errors:e.errors,warnings:e.warnings||[]};render();return;}render();}throw e;}}
document.addEventListener('change',ev=>{const el=ev.target;if(!el.matches('[data-plan-map]'))return;try{requireAccess(true);if(el.value==='?')return;const p=state.preview,mapping={...p.mapping,[el.dataset.planMap]:el.value};state.preview=FinancePlan.preview(getData(),p.plan,mapping);render();}catch(e){noticeError(e);}});
async function downloadWorkbook(wb,name){try{const src=getShareLogoSrc();if(src.startsWith('data:image/')){const id=wb.addImage({base64:src,extension:src.includes('image/png')?'png':'jpeg'});const sheet=wb.getWorksheet('Jaarplanning')||wb.getWorksheet('Uitleg')||wb.getWorksheet('Jaaroverzicht');if(sheet){const img=new Image();await new Promise((ok,no)=>{img.onload=ok;img.onerror=no;img.src=src;});const h=55,w=h*img.naturalWidth/img.naturalHeight;sheet.addImage(id,{tl:{col:sheet.name==='Jaarplanning'?13:3,row:0},ext:{width:w,height:h}});}}}catch(_){}const bytes=await wb.xlsx.writeBuffer();triggerBlobDownload(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),name);}
async function template(){requireAccess(true);const pairs=FinancePlan.duplicates(getData(),state.year);if(pairs.length&&!confirm('Er zijn '+pairs.length+' mogelijk dubbele wedstrijdparen. Annuleren opent de controle per paar. Toch nu downloaden?')){state.view='duplicates';render();return;}const wb=await FinancePlan.workbook(ExcelJS,getData(),state.year);await downloadWorkbook(wb,'HSV_GHW_Jaarplanning_'+state.year+'.xlsx');}
async function action(name,el){
 if(name==='today'){if(!isAdmin)throw Error('Log eerst in.');const d=getData(),list=todayMatches(d);if(!list.length)throw Error('Er staat vandaag geen wedstrijd in de agenda.');if(list.length===1)return openToday(list[0]);const box=byId('fin-today-list');if(box)box.innerHTML=list.map((m,i)=>button(m.title,'today-pick',`data-index="${i}"`)).join('');return;}
 if(name==='today-pick'){const list=todayMatches(getData());return openToday(list[Number(el.dataset.index)]);}
 requireAccess();const d=getData(),e=currentEntry(d);
 switch(name){
 case 'open':state.view='overview';nav('finance');return;
 case 'back':state.view='overview';state.detail=null;render();return;
 case 'detail':openDetail(el.dataset.id);return;
 case 'budget':requireAccess(true);state.view='budget';render();return;
 case 'new':newExpense();return;
 case 'rights':if(!isHoofdAdmin())throw Error('Alleen de hoofdbeheerder beheert rechten.');state.view='rights';render();return;
 case 'import':requireAccess(true);state.view='import';state.preview=null;state.importErrors=null;nav('finance');return;
 case 'waters':requireAccess();state.view='waters';render();return;
 case 'remove-water':requireAccess(true);if(!confirm('Viswater "'+el.dataset.name+'" uit de tabel verwijderen? Bestaande wedstrijden veranderen niet.'))return;FinanceWaters.remove(d,el.dataset.name);save(d);render();return;
 case 'duplicates':requireAccess(true);state.view='duplicates';render();return;
 case 'resolve-duplicate':requireAccess(true);save(FinancePlan.resolveDuplicate(d,state.year,el.dataset.key,el.dataset.choice));render();showAppNotice(el.dataset.choice==='separate'?'De wedstrijden blijven apart.':'Gekoppeld. De volgende download bevat één regel voor deze wedstrijd.');return;
 case 'template':await template();return;
 case 'clear-import':state.preview=null;state.importErrors=null;render();return;
 case 'apply-import':{requireAccess(true);if(!state.preview)throw Error('Kies eerst een bestand.');if(localStorage.getItem(SK)!==state.planSnapshot)throw Error('Gegevens zijn sinds de controle gewijzigd. Upload het bestand opnieuw om de actuele verschillen te controleren.');const chosen=[...document.querySelectorAll('[data-fin-import]:checked')].map(x=>Number(x.dataset.finImport)),remove=[...document.querySelectorAll('[data-plan-remove]:checked')].map(x=>x.dataset.planRemove);if(!chosen.length&&!remove.length)throw Error('Er zijn geen wijzigingen geselecteerd.');save(FinancePlan.apply(d,state.preview,chosen,remove));state.year=state.preview.year;state.preview=null;state.view='overview';render();showAppNotice('Agenda en begroting bijgewerkt. Een nieuwe download bevat de actuele gegevens.');return;}
 case 'settle-open':{requireAccess(true);const t=d.finance.entries.find(x=>x.id===el.dataset.entry);if(!t)throw Error('Post niet gevonden.');if(el.dataset.kind==='series')C.setSeriesPaid(d,t.id,el.dataset.unit,true);else C.setUnpaid(t,el.dataset.unit,false);save(d);render();showAppNotice('Als betaald gemarkeerd.');return;}
 case 'cancel':requireAccess(true);if(e.kind==='match'&&e.matchId&&(d.uitslagen||[]).some(u=>C.matchIds(d,e.matchId).includes(u.wedstrijdId)))throw Error('Deze wedstrijd heeft al een uitslag en kan niet vervallen.');if(!confirm('Deze post laten vervallen? Hij telt dan niet meer mee in de begroting.'))return;C.cancel(e);if(e.kind==='series')for(const c of d.finance.entries.filter(c=>c.seriesId===e.id))C.cancel(c);const a=d.roosterItems.find(a=>a.id===e.agendaId);if(a)a.zichtbaar=false;save(d);state.view='overview';render();return;
 case 'participants':requireAccess(true);if(onlyFinance())throw Error('Open de wedstrijd via het uitslagenbeheer.');nav('invoer');openInvoer(el.dataset.id);return;
 case 'start-match':requireAccess(true);if(onlyFinance())throw Error('Laat een wedstrijdbeheerder de wedstrijd eerst starten vanuit de agenda.');nav('invoer');maakWedstrijdVanRoosterItem(el.dataset.id);return;
 case 'backup':requireAccess(true);exporteerBackup();return;
 }
}
function afterPaymentChange(el){if(el.closest('.fin-pay-panel'))mountPayments();else render();}
async function change(el){
 const kind=el.dataset.finChange;
 if(kind==='year'){const y=Number(el.value);if(!Number.isInteger(y)||y<2000||y>2100)throw Error('Kies een jaar tussen 2000 en 2100.');state.year=y;render();return;}
 if(kind==='permission'||kind==='finance-only'){if(!isHoofdAdmin())throw Error('Alleen de hoofdbeheerder beheert rechten.');const d=getData(),a=d.admins.find(a=>a.id===el.dataset.id);if(a.rol==='hoofd')return;if(kind==='permission')a.financeAccess=el.value;else a.financeOnly=el.checked;saveData(d);updateAdminUi();return;}
 if(kind==='aow'){if(!isAdmin)throw Error('Log eerst in.');const d=getData(),v=d.vissers.find(v=>v.id===el.dataset.id);if(!v)throw Error('Visser niet gevonden.');v.aow=el.checked;saveData(d);return;}
 if(kind==='series-mode'){if(!isAdmin)throw Error('Log eerst in.');const d=getData();if(!el.value)return;C.setSeriesMode(d,el.dataset.id,el.dataset.member,el.value);saveData(d);afterPaymentChange(el);return;}
 if(kind==='series-paid'){if(!isAdmin)throw Error('Log eerst in.');const d=getData();C.setSeriesPaid(d,el.dataset.id,el.dataset.member,el.checked);saveData(d);afterPaymentChange(el);return;}
 if(kind==='unpaid'){if(!isAdmin)throw Error('Log eerst in.');const d=getData(),e=d.finance.entries.find(e=>e.id===el.dataset.id);if(!e)throw Error('Wedstrijd niet gevonden.');C.setUnpaid(e,el.dataset.unit,el.checked);saveData(d);afterPaymentChange(el);return;}
 if(el.dataset.waterField){requireAccess(true);const d=getData(),rowEl=el.closest('[data-water]'),w=FinanceWaters.find(d,rowEl.dataset.water);if(!w)throw Error('Viswater niet gevonden.');const f=el.dataset.waterField,v=el.value.trim();
  if(f==='name'){if(!v)throw Error('Naam mag niet leeg zijn.');if(FinanceWaters.find(d,v)&&FinanceWaters.find(d,v)!==w)throw Error('Dit viswater bestaat al.');w.name=v;}
  else if(['gather','start','end'].includes(f)){if(v&&!/^([01]?\d|2[0-3])[:.][0-5]\d$/.test(v))throw Error('Gebruik een tijd zoals 08:30.');w[f]=v?v.replace('.',':').padStart(5,'0'):'';}
  else w[f]=v;save(d);render();return;}
 if(el.id==='fin-import-file')await readImport(el.files[0]);
}
function submit(form){
 requireAccess(true);const d=getData(),e=currentEntry(d);
 if(form.id==='fin-budget-form'){const extras=[...form.querySelectorAll('.fin-extra-row')].map(r=>({title:r.querySelector('[data-extra-title]').value.trim(),amount:C.cents(r.querySelector('[data-extra-amount]').value)})).filter(x=>x.title||x.amount);if(extras.some(x=>!x.title))throw Error('Geef elke extra bijdrage een omschrijving.');d.finance.years[state.year]={budget:C.cents(read('fin-budget')),carry:C.cents(read('fin-carry')),extras,configured:true};save(d);state.view='overview';}
 if(form.id==='fin-water-form'){FinanceWaters.upsert(d,{name:read('fin-water-name'),location:read('fin-water-location')});save(d);}
 if(form.id==='fin-entry-form'){
  const title=read('fin-title').trim();if(!title)throw Error('Vul een omschrijving in.');const planned=C.cents(read('fin-planned')),actual=C.cents(read('fin-actual'));
  Object.assign(e,{title,planned,configured:true});e.actual=null;e.actual=actual===C.pot(d,e)?null:actual;
  if(e.kind!=='series'){const date=byId('fin-date')?(read('fin-date')?C.date(read('fin-date')):''):e.date;if(e.kind==='match'&&!date)throw Error('Een wedstrijd heeft een datum nodig.');e.date=date;e.year=Number((date||'').slice(0,4))||e.year||state.year;}
  if(e.kind==='match'&&!e.seriesId){e.fee=C.cents(read('fin-fee'));if(byId('fin-fee-basis'))e.feeBasis=read('fin-fee-basis');}
  if(e.kind==='series'){Object.assign(e,{looseFee:C.cents(read('fin-series-loose')),looseFeeAow:C.cents(read('fin-series-loose-aow')),fee:C.cents(read('fin-series-fee')),feeAow:C.cents(read('fin-series-aow'))});const old=e.title;for(const c of d.finance.entries.filter(c=>c.seriesId===e.id)){const a=d.roosterItems.find(a=>a.id===c.agendaId);if(a&&a.serieNaam===old)a.serieNaam=title;const w=(d.wedstrijden||[]).find(w=>w.id===c.matchId),comp=(d.competities||[]).find(c2=>c2.id===w?.competitieId);if(comp&&comp.naam===old)comp.naam=title;}e.seriesKey=state.year+':'+title.trim().toLocaleLowerCase('nl');}
  else{const r=d.roosterItems.find(r=>r.id===e.agendaId);if(r){r.titel=title;r.autoTitel=false;if(e.date)r.datum=e.date;}for(const wid of C.matchIds(d,e.matchId)){const w=d.wedstrijden.find(w=>w.id===wid);if(w){w.naam=title;if(e.date)w.datum=e.date;}}}
  save(d);
 }
 if(form.id==='fin-user-form'){if(!isHoofdAdmin())throw Error('Alleen de hoofdbeheerder beheert accounts.');const name=read('fin-user-name').trim(),code=read('fin-user-code').trim();if(!name||code.length<4)throw Error('Vul een naam en een code van minimaal vier tekens in.');d.admins.push({id:uid(),naam:name,code,rol:'admin',actief:true,financeOnly:true,financeAccess:read('fin-user-right')});save(d);if(state.view!=='rights')renderBeheer();}
 render();showAppNotice('Opgeslagen.');
}
document.addEventListener('click',ev=>{const el=ev.target.closest('[data-fin]');if(el){ev.preventDefault();Promise.resolve(action(el.dataset.fin,el)).catch(noticeError);}});
document.addEventListener('change',ev=>{if(ev.target.matches('[data-fin-change],[data-water-field],#fin-import-file'))Promise.resolve(change(ev.target)).catch(err=>{noticeError(err);if(['unpaid','series-mode','series-paid'].includes(ev.target.dataset.finChange))afterPaymentChange(ev.target);});});
document.addEventListener('submit',ev=>{if(ev.target.id.startsWith('fin-')){ev.preventDefault();try{submit(ev.target);}catch(err){noticeError(err);}}});
const originalImport=renderImport;renderImport=function(){originalImport();if(allowed(true))byId('pv-import').insertAdjacentHTML('afterbegin',`<div class="card"><h2>Jaaragenda en begroting</h2><p>Importeer geplande wedstrijden en uitgaven via Financiën.</p>${button('Jaarplanning importeren','import')}</div>`);};
const oldBackupRender=renderBackup;renderBackup=function(){if(!isHoofdAdmin()){showAppNotice('Alleen de hoofdbeheerder beheert volledige back-ups.','warn');return;}oldBackupRender();};
exporteerBackup=function(){if(!isHoofdAdmin()){showAppNotice('Alleen de hoofdbeheerder kan een volledige back-up maken.','warn');return;}const data=getData(),meta=maakBackupMetadata(data);triggerBlobDownload(new Blob([JSON.stringify({meta,data},null,2)],{type:'application/json'}),'HSV_GHW_backup_'+new Date().toISOString().slice(0,10)+'.json');showAppNotice('Back-up inclusief financiën gedownload.');};
const oldRestore=bevestigHerstel;bevestigHerstel=function(){if(!isHoofdAdmin())return;oldRestore();doLogout();};
const oldWipe=wisAlles;wisAlles=function(){if(!isHoofdAdmin())return;oldWipe();};
const oldPlanning=getRoosterPlanningItems;getRoosterPlanningItems=function(d){return oldPlanning(d).map(r=>{const e=d.finance?.entries.find(e=>e.agendaId===r.id);return e?.status==='cancelled'?{...r,titel:'Afgelast · '+r.titel}:r;});};
const oldStart=maakWedstrijdVanRoosterItem;maakWedstrijdVanRoosterItem=function(id){const e=getData().finance.entries.find(e=>e.agendaId===id);if(e?.status==='cancelled'){showAppNotice('Deze wedstrijd is vervallen. Heropen hem eerst via de jaarplanning.','warn');return;}oldStart(id);};
// AOW flag per fisher, maintained in the fishers list.
const oldVissers=renderBVissers;renderBVissers=function(){oldVissers();const d=getData();document.querySelectorAll('#bv-vissers tr[data-visser-id]').forEach(tr=>{const v=d.vissers.find(v=>v.id===tr.dataset.visserId),td=tr.children[1];if(!v||!td||td.querySelector('[data-fin-change="aow"]'))return;td.insertAdjacentHTML('beforeend',`<label class="fin-aow"><input type="checkbox" data-fin-change="aow" data-id="${A(v.id)}" ${v.aow?'checked':''}> AOW-tarief</label>`);});};
window.Finance={render,access,allowed,openDetail,state,summary:()=>C.summary(getData(),state.year),open:()=>C.open(getData(),state.year)};
updateAdminUi();
})();
