let playwright;try{playwright=require('playwright');}catch(_){playwright=require('C:/Users/grootest/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');}
const {chromium}=playwright;const ExcelJS=require('../exceljs.min.js'),fs=require('fs'),path=require('path'),os=require('os'),assert=require('node:assert/strict'),{pathToFileURL}=require('url');
const out=path.join(os.tmpdir(),'hsv-finance-plan-test');fs.mkdirSync(out,{recursive:true});
const row=(form,name,serie,date,water,loc,g,s,e,b,f,sf,aow,laow)=>[form,name,serie,date,null,water,loc,g,s,e,null,b,f,sf,aow,laow];
const clear=(ws,from=8,to=80)=>{for(let n=from;n<=to;n++)ws.getRow(n).values=[];};
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage({viewport:{width:1400,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**',r=>r.abort());await page.goto(pathToFileURL(path.join(__dirname,'..','index.html')).href);await page.locator('#admin-entry-btn').click();await page.locator('#pin-admin-select').selectOption('head-admin');await page.locator('#pin-inp').fill('1234');await page.getByRole('button',{name:'Inloggen',exact:true}).click();await page.locator('#nav-finance').click();await page.locator('#fin-year').fill('2026');await page.locator('#fin-year').dispatchEvent('change');const click=a=>page.locator('#pv-finance [data-fin="'+a+'"]').first().click();
async function download(name){const pending=page.waitForEvent('download');await click('template');const dl=await pending,file=path.join(out,name);await dl.saveAs(file);const wb=new ExcelJS.Workbook();await wb.xlsx.load(fs.readFileSync(file));return wb;}
async function upload(wb,expect='Controleer de verschillen'){const buffer=Buffer.from(await wb.xlsx.writeBuffer());await click('import');await page.locator('#fin-import-file').setInputFiles({name:'plan.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer});await page.getByText(expect).first().waitFor();}
// Empty 2026: two sheets, logo, budget hint, 2026 club budget lines appended as yellow rows.
let wb=await download('empty.xlsx');assert.deepEqual(wb.worksheets.map(w=>w.name),['Jaarplanning','Viswateren']);let ws=wb.getWorksheet('Jaarplanning');assert.equal(ws.getImages().length,1);assert.equal(ws.getCell('D2').value,2435);assert.equal(ws.getCell('A8').value,'Serie');assert.equal(ws.getCell('C8').value,'Winterserie');
// Fill a small plan: series with amounts on row 2 and no names, a couple match, an expense, a water with defaults.
clear(ws);ws.getRow(8).values=row('Serie','','Winterserie','03-10-2026','Binnenmaas','',null,null,null);ws.getRow(9).values=row('Serie','','Winterserie','10-10-2026','Spui','Clubhuis','07:30','08:00','12:00',40,10,25,15);ws.getRow(10).values=row('Serie','','Winterserie','17-10-2026','Binnenmaas','',null,null,null);ws.getRow(11).values=row('Koppel','Spui koppel 1','','05-04-2026','Spui','',null,null,null,30,10);ws.getRow(12).values=['Overige uitgave','Inkt/papier',null,null,null,null,null,null,null,null,null,250];
wb.getWorksheet('Viswateren').getRow(2).values=['Binnenmaas','Parkeerplaats Mijnsheerenland','07:00','08:00','11:30'];
await upload(wb);assert(await page.getByText('Jaarbudget 2026').isVisible());assert.equal(await page.locator('[data-fin-import]:checked').count(),5);await page.screenshot({path:path.join(out,'preview-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,'preview-mobile.png'),fullPage:true});await page.setViewportSize({width:1400,height:1000});
await click('apply-import');const s=await page.evaluate(()=>Finance.summary());assert.equal(s.budget,243500);assert.equal(s.planned,4000+3000+25000);let d=await page.evaluate(()=>getData());assert.equal(d.finance.waters.length,1);const w1=d.roosterItems.find(a=>a.serieWedstrijdNummer===1);assert.equal(w1.locatie,'Parkeerplaats Mijnsheerenland');assert.equal(w1.starttijd,'08:00');assert.equal(w1.titel,'');assert.equal(d.finance.entries.find(e=>e.kind==='series').feeAow,1500);
// Public schedule shows the auto title and fisher tariffs, not the club contribution.
const items=await page.evaluate(()=>getRoosterPlanningItems(getData()));assert(items.some(i=>i.titel==='Winterserie - wedstrijd 1'||i.titel===''));const line=await page.evaluate(()=>getRoosterTijdRegel(getRoosterPlanningItems(getData())[0]));assert(!line.includes('40,00'));
// Round trip is unchanged; the club budget lines that are not planned yet come back as rows to resolve.
wb=await download('populated.xlsx');ws=wb.getWorksheet('Jaarplanning');assert.equal(ws.getCell('B9').value,'Winterserie - wedstrijd 1');assert.equal(ws.getCell('L9').value,40);assert.equal(ws.getCell('O9').value,15);assert.equal(ws.getCell('L10').value,null);assert.equal(wb.getWorksheet('Viswateren').getCell('B2').value,'Parkeerplaats Mijnsheerenland');
await upload(wb);assert.equal(await page.locator('[data-fin-import]:checked').count(),0);assert((await page.locator('.fin-import-row.error').count())>0);await click('clear-import');
// All errors at once, per row and column, nothing changed.
ws.getCell('J10').value='25:00';ws.getCell('L8').value='abc';clear(ws,13);await upload(wb,'fouten in het bestand');assert.equal(await page.locator('.fin-errors tbody tr').count(),2);assert(await page.getByText('Eindtijd').first().isVisible());assert.equal((await page.evaluate(()=>Finance.summary())).planned,s.planned);
// Waters view: edit a time inline and add a water.
await click('back');await click('waters');await page.locator('[data-water-field="gather"]').first().fill('06.45');await page.locator('[data-water-field="gather"]').first().dispatchEvent('change');assert.equal(await page.evaluate(()=>getData().finance.waters[0].gather),'06:45');await page.locator('#fin-water-name').fill('Spui');await page.locator('#fin-water-location').fill('Parkeerplaats Spui');await page.locator('#fin-water-form button').click();assert.equal(await page.evaluate(()=>getData().finance.waters.length),2);
// App edits appear in the next download; 2027 download proposes this year's matches without dates.
await click('back');await page.locator('.fin-row').filter({hasText:'Inkt/papier'}).click();await page.locator('#fin-planned').fill('135');await page.locator('#fin-entry-form button').click();await click('back');wb=await download('app-edited.xlsx');assert.equal(wb.getWorksheet('Jaarplanning').getCell('L13').value,135);
await page.locator('#fin-year').fill('2027');await page.locator('#fin-year').dispatchEvent('change');wb=await download('proposal-2027.xlsx');ws=wb.getWorksheet('Jaarplanning');assert.equal(ws.getCell('B2').value,2027);assert.match(String(ws.getCell('A5').value),/voorstel/);assert.equal(ws.getCell('D8').value,null);assert.equal(ws.getCell('R8').value||null,null);
await page.reload();assert.equal(await page.evaluate(()=>getData().finance.waters.length),2);assert.deepEqual(errors,[]);console.log('PASS: real browser download/upload with two sheets, budget cells, auto titles, water defaults, error table, waters editor, app edits, 2027 proposal, mobile preview');console.log(out);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
