const assert=require('node:assert/strict'),ExcelJS=require('../lib/exceljs.min.js'),P=require('../lib/finance-plan.js'),C=require('../lib/finance-series.js'),W=require('../lib/finance-waters.js');require('../lib/finance-begroting-2026.js');
const empty=()=>({roosterItems:[],wedstrijden:[],competities:[],uitslagen:[]});
const row=(form,name,serie,date,water,loc,g,s,e,b,f,sf,aow,laow)=>[form,name,serie,date,null,water,loc,g,s,e,null,b,f,sf,aow,laow];
const clear=(ws,from=8,to=60)=>{for(let n=from;n<=to;n++)ws.getRow(n).values=[];};
const lineOf=(ws,title)=>{let n=0;ws.eachRow((r,i)=>{if(i>=8&&String(r.getCell(2).value||'')===title)n=i;});return n;};
const reload=async wb=>{const again=new ExcelJS.Workbook();await again.xlsx.load(await wb.xlsx.writeBuffer());return again;};
(async()=>{
// Download: two sheets, budget cells, hidden link column, 2026 hints appended on an empty year.
let d=empty(),wb=await P.workbook(ExcelJS,d,2026),ws=wb.getWorksheet('Jaarplanning');
assert.deepEqual(wb.worksheets.map(w=>w.name),['Jaarplanning','Viswateren']);assert.equal(ws.getCell('B2').value,2026);assert.equal(ws.getCell('D2').value,2435);assert.equal(ws.getColumn(18).hidden,true);assert.equal(ws.getCell('Q7').value,'Uitbetaald / uitgegeven');assert.equal(ws.getCell('P7').value,'Inleg los AOW');
assert.equal(ws.actualRowCount-7,P.hints[2026].length-1);assert.deepEqual(ws.getRow(8).values.slice(1,4),['Serie','','Winterserie']);
// Fill: series with amounts on the second row, empty names, water defaults, a couple match, an expense, a row without form, a water row.
clear(ws);
ws.getRow(8).values=row('Serie','','Winterserie','03-10-2026','Binnenmaas','',null,null,null,null,null,null,null);
ws.getRow(9).values=row('Serie','','Winterserie','10-10-2026','Spui','Clubhuis','07:30','08:00','12:00',40,10,25,15,8);
ws.getRow(10).values=row('Serie','Winter finale','Winterserie','17-10-2026','Binnenmaas','',null,null,null,null,null,null,null);
ws.getRow(11).values=row('Koppel','Spui koppel 1','','05-04-2026','Spui','',null,null,null,30,10,null,null);ws.getRow(14).values=row('Koppel','','','20-09-2026','Spui','',null,null,null,30,10,null,null);
ws.getRow(12).values=['Overige uitgave','Inkt/papier',null,null,null,null,null,null,null,null,null,250];
ws.getRow(13).values=['','Jeugddag',null,null,null,null,null,null,null,null,null,500];
ws.getCell('D2').value=2435;wb.getWorksheet('Viswateren').getRow(2).values=['Binnenmaas','Parkeerplaats','07:00','08:00','11:30'];
let plan=P.read(wb);assert.equal(plan.warnings.length,1);assert.match(plan.warnings[0],/Jeugddag/);assert.equal(plan.budget,243500);assert.equal(plan.rows.length,6);assert.equal(plan.rows.find(r=>r.line===14).title,'Koppel Spui');
let p=P.preview(d,plan);assert(p.items.every(i=>i.action==='new'));assert.equal(p.items[0].row.title,'Winterserie · Binnenmaas');assert.equal(p.items[1].row.title,'Winterserie · Spui');assert.equal(p.items[0].row.location,'Parkeerplaats');assert.equal(p.items[0].row.start,'08:00');assert.equal(p.items[1].row.location,'Clubhuis');assert.equal(p.budget[0].after,243500);
d=P.apply(d,p,p.items.map(i=>i.row.line));
const s=C.summary(d,2026);assert.equal(s.budget,243500);assert.equal(s.planned,4000+3000+3000+25000);assert.equal(s.missing,0);assert.equal(d.roosterItems.find(a=>a.datum==='2026-09-20').titel,'Koppel Spui');assert.equal(d.roosterItems.find(a=>a.datum==='2026-09-20').autoTitel,true);
const parent=d.finance.entries.find(e=>e.kind==='series');assert.deepEqual([parent.planned,parent.fee,parent.looseFee,parent.feeAow,parent.looseFeeAow,parent.configured],[4000,2500,1000,1500,800,true]);
assert.equal(d.roosterItems.filter(a=>a.serieNaam==='Winterserie').length,3);assert.equal(d.finance.entries.find(e=>e.title==='Spui koppel 1').feeBasis,'koppel');assert.equal(W.find(d,'binnenmaas').location,'Parkeerplaats');
// Roundtrip: existing rows unchanged; unmatched 2026 hints come back as rows needing a date or a link.
let again=await reload(await P.workbook(ExcelJS,d,2026));p=P.preview(d,P.read(again));
assert.equal(p.items.filter(i=>i.action==='same').length,6);assert.equal(again.getWorksheet('Jaarplanning').getCell(lineOf(again.getWorksheet('Jaarplanning'),'Spui koppel 1'),2).value,'Spui koppel 1');assert(!p.items.some(i=>i.row.title==='Spui koppel 2'&&i.action!=='same'||i.row.title==='Koppel Spui'&&i.action!=='same'));assert(p.items.filter(i=>i.action==='error').every(i=>!i.row.date&&!i.candidates));assert(!p.items.some(i=>i.row.title==='Inkt/papier'&&i.action!=='same'));
assert.throws(()=>P.apply(d,p,p.items.map(i=>i.row.line)),/Los eerst op/);
// Optional fields: blank Begroot means "still to fill", blank water/times allowed.
ws=again.getWorksheet('Jaarplanning');clear(ws,13);let k=lineOf(ws,'Spui koppel 1');ws.getCell(k,12).value=null;plan=P.read(again);p=P.preview(d,plan);const koppel=p.items.find(i=>i.row.title==='Spui koppel 1');assert.equal(koppel.action,'update');let next=P.apply(d,p,[k]);assert.equal(next.finance.entries.find(e=>e.title==='Spui koppel 1').configured,false);assert.equal(C.summary(next,2026).missing,1);
// Changed identity keeps receipts and results; hand-linked budget line inherits the date.
const e=d.finance.entries.find(e=>e.title==='Spui koppel 1');e.unpaid.v1=true;e.matchId='w1';d.roosterItems.find(r=>r.id===e.agendaId).gekoppeldeWedstrijdId='w1';d.wedstrijden.push({id:'w1',naam:e.title,datum:e.date,isKoppel:true});d.uitslagen.push({wedstrijdId:'w1',visserId:'v1',gewicht:1500});
again=await reload(await P.workbook(ExcelJS,d,2026));ws=again.getWorksheet('Jaarplanning');clear(ws,13);k=lineOf(ws,'Spui koppel 1');ws.getCell(k,2).value='Spui koppelwedstrijd voorjaar';ws.getCell(k,12).value=55;
p=P.preview(d,P.read(again));next=P.apply(d,p,[k]);const renamed=next.finance.entries.find(x=>x.id===e.id);assert.equal(renamed.title,'Spui koppelwedstrijd voorjaar');assert.equal(renamed.planned,5500);assert.equal(renamed.unpaid.v1,true);assert.deepEqual(next.uitslagen,d.uitslagen);assert.equal(next.wedstrijden[0].naam,'Spui koppelwedstrijd voorjaar');
ws.getCell(k,18).value=null;ws.getCell(k,2).value='Spui koppel 2';ws.getCell(k,4).value=null;p=P.preview(d,P.read(again));const loose=p.items.find(i=>i.row.line===k);assert.equal(loose.action,'error');assert(loose.candidates.length);
p=P.preview(d,P.read(again),{[k]:e.id});const linked=p.items.find(i=>i.row.line===k);assert.equal(linked.action,'update');assert.equal(linked.row.date,'2026-04-05');assert.equal(P.apply(d,p,[k]).finance.entries.filter(x=>x.kind==='match').length,5);
// A stale hidden link (post deleted in the app) falls back to identity matching with a warning instead of failing.
{const stale=await reload(await P.workbook(ExcelJS,d,2026));const sw=stale.getWorksheet('Jaarplanning');clear(sw,14);const kk=lineOf(sw,'Spui koppel 1');sw.getCell(kk,18).value='match-verwijderd';const sp=P.preview(d,P.read(stale));assert.equal(sp.items.find(i=>i.row.line===kk).action,'same');assert.match(sp.warnings.join(' '),/bestaat niet meer/);}
// Identity is date + form + water: a renamed row without link is still recognised; blank name derives one.
again=await reload(await P.workbook(ExcelJS,d,2026));ws=again.getWorksheet('Jaarplanning');clear(ws,14);k=lineOf(ws,'Spui koppel 1');ws.getCell(k,18).value=null;ws.getCell(k,2).value=null;p=P.preview(d,P.read(again));const auto=p.items.find(i=>i.row.line===k);assert.equal(auto.action,'update');assert.equal(auto.id,e.id);assert.deepEqual(auto.changes.map(c=>c.key),['title']);assert.equal(auto.row.title,'Koppel Spui');
// Missing rows are kept unless the user cancels them; rows with results cannot be cancelled.
again=await reload(await P.workbook(ExcelJS,d,2026));ws=again.getWorksheet('Jaarplanning');clear(ws,14);ws.getRow(lineOf(ws,'Inkt/papier')).values=[];ws.getRow(lineOf(ws,'Spui koppel 1')).values=[];p=P.preview(d,P.read(again));assert.equal(p.missing.length,2);assert.equal(P.apply(d,p,[]).finance.entries.find(x=>x.title==='Inkt/papier').status,'planned');assert.equal(P.apply(d,p,[],[p.missing.find(m=>m.title==='Inkt/papier').id]).finance.entries.find(x=>x.title==='Inkt/papier').status,'cancelled');assert.throws(()=>P.apply(d,p,[],[e.id]),/uitslagen/);
// All errors at once, each with row and column; different series amounts rejected; legacy columns still readable.
again=await reload(await P.workbook(ExcelJS,d,2026));ws=again.getWorksheet('Jaarplanning');clear(ws,14);let w1=lineOf(ws,'')+0,w2=0,w3=lineOf(ws,'Winter finale');ws.eachRow((r,i)=>{if(i>=8&&r.getCell(3).value==='Winterserie'&&!r.getCell(2).value){if(!w1||i<w1)w1=i;}});w2=w1+1;k=lineOf(ws,'Spui koppel 1');ws.getCell(w2,10).value='25:00';ws.getCell(w3,4).value='17-10-2025';ws.getCell(k,12).value='abc';ws.getCell(w3,12).value=99;
try{P.read(again);assert.fail('expected errors');}catch(err){assert.equal(err.errors.length,4);assert.deepEqual(err.errors.map(x=>x.line+':'+x.column).sort(),[w2+':Eindtijd',w3+':Datum',k+':Begroot',w1+':Begroot'].sort());}
const legacy=new ExcelJS.Workbook(),lw=legacy.addWorksheet('Jaarplanning');lw.getCell('B2').value=2026;lw.getRow(7).values=['Soort','Wedstrijdnaam / omschrijving','Datum','Einddatum','Wedstrijdvorm','Serie','Hengeltype','Viswater','Locatie loting','Lotingtijd','Starttijd','Eindtijd','Begroot','Inleg per wedstrijd','Inleg hele serie'];lw.getRow(8).values=['Wedstrijd','Oud formaat','20-06-2026',null,'Individueel','','Vrij','Binnenmaas','Clubhuis','07:30','08:00','12:00',30,10,null];lw.getRow(9).values=['Overige uitgave','Weegschaal',null,null,null,null,null,null,null,null,null,null,100];
plan=P.read(legacy);assert.deepEqual(plan.rows.map(r=>[r.form,r.title,r.fee,r.planned]),[['solo','Oud formaat',1000,3000],['expense','Weegschaal',null,10000]]);
// Series rename via Excel and the proposal for a year without matches.
again=await reload(await P.workbook(ExcelJS,d,2026));ws=again.getWorksheet('Jaarplanning');clear(ws,14);ws.eachRow((r,n)=>{if(n>=8&&r.getCell(3).value==='Winterserie')r.getCell(3).value='Nieuwe winterserie';});const rp=P.preview(d,P.read(again)),rd=P.apply(d,rp,rp.items.filter(i=>i.action!=='same').map(i=>i.row.line));assert.equal(rd.finance.entries.filter(x=>x.kind==='series').length,1);assert.equal(rd.finance.entries.find(x=>x.kind==='series').title,'Nieuwe winterserie');assert.equal(C.summary(rd,2026).planned,4000+3000+3000+25000);
const w27=await P.workbook(ExcelJS,d,2027),s27=w27.getWorksheet('Jaarplanning');assert.match(String(s27.getCell('A5').value),/voorstel/);{let n=0;s27.eachRow((r,i)=>{if(i>=8&&r.getCell(1).value)n++;});assert.equal(n,6);}assert.equal(s27.getRow(8).getCell(4).value,null);assert.equal(s27.getRow(8).getCell(18).value||null,null);assert.equal(s27.getRow(8).getCell(12).value,30);
console.log('PASS: auto names from form+water, identity by date+form+water, two sheets, few mandatory fields, series amounts anywhere, auto titles, water defaults, budget cells, hints, hand-linking, all errors at once, legacy columns, rename, proposal');
})().catch(e=>{console.error(e);process.exit(1)});
